const preguntasBiblia = [
  { categoria: "Biblia", pregunta: "¿Quién construyó el arca?", opciones: ["Moisés", "Noé", "Abraham", "David"], respuesta: "Noé" },
  { categoria: "Biblia", pregunta: "¿En qué ciudad nació Jesús?", opciones: ["Nazaret", "Jerusalén", "Belén", "Capernaum"], respuesta: "Belén" },
  { categoria: "Biblia", pregunta: "¿Quién fue tragado por un gran pez?", opciones: ["Jonás", "Elías", "José", "Daniel"], respuesta: "Jonás" },
  { categoria: "Biblia", pregunta: "¿Quién recibió los Diez Mandamientos en el monte Sinaí?", opciones: ["Abraham", "Moisés", "Josué", "David"], respuesta: "Moisés" },
  { categoria: "Biblia", pregunta: "¿Quién negó a Jesús tres veces antes del canto del gallo?", opciones: ["Juan", "Pedro", "Santiago", "Tomás"], respuesta: "Pedro" },
  { categoria: "Biblia", pregunta: "¿Cuál fue el primer milagro de Jesús?", opciones: ["Sanar a un ciego", "Resucitar a Lázaro", "Convertir agua en vino", "Multiplicar panes"], respuesta: "Convertir agua en vino" },
  { categoria: "Biblia", pregunta: "¿Quién fue el primer rey de Israel?", opciones: ["Saúl", "David", "Salomón", "Josué"], respuesta: "Saúl" },
  { categoria: "Biblia", pregunta: "¿Qué apóstol dudó de la resurrección de Jesús hasta verlo?", opciones: ["Pedro", "Andrés", "Tomás", "Felipe"], respuesta: "Tomás" },
  { categoria: "Biblia", pregunta: "¿Quién fue lanzado al foso de los leones?", opciones: ["Daniel", "José", "Ezequiel", "Samuel"], respuesta: "Daniel" },
  { categoria: "Biblia", pregunta: "¿Cuál era el oficio de Mateo antes de seguir a Jesús?", opciones: ["Carpintero", "Recaudador de impuestos", "Pescador", "Pastor"], respuesta: "Recaudador de impuestos" },
  { categoria: "Biblia", pregunta: "¿Quién fue la madre de Jesús?", opciones: ["María Magdalena", "María", "Elisabet", "Ana"], respuesta: "María" },
  { categoria: "Biblia", pregunta: "¿Cómo se llamaba el hermano de Moisés?", opciones: ["Josué", "Aarón", "Samuel", "Isaac"], respuesta: "Aarón" },
  { categoria: "Biblia", pregunta: "¿Dónde fue crucificado Jesús?", opciones: ["Monte Carmelo", "Monte Sinaí", "Monte de los Olivos", "Gólgota"], respuesta: "Gólgota" },
  { categoria: "Biblia", pregunta: "¿Quién mató al gigante Goliat?", opciones: ["David", "Saúl", "Sansón", "Elías"], respuesta: "David" },
  { categoria: "Biblia", pregunta: "¿Quién escribió la mayoría de las cartas del Nuevo Testamento?", opciones: ["Pedro", "Juan", "Pablo", "Santiago"], respuesta: "Pablo" },
  { categoria: "Biblia", pregunta: "¿Cuál fue la primera pareja creada por Dios?", opciones: ["Abraham y Sara", "Adán y Eva", "Isaac y Rebeca", "José y María"], respuesta: "Adán y Eva" },
  { categoria: "Biblia", pregunta: "¿Qué apóstol caminó sobre el agua hacia Jesús?", opciones: ["Pedro", "Juan", "Andrés", "Felipe"], respuesta: "Pedro" },
  { categoria: "Biblia", pregunta: "¿Quién interpretó los sueños del faraón en Egipto?", opciones: ["José", "Daniel", "Moisés", "Aarón"], respuesta: "José" },
  { categoria: "Biblia", pregunta: "¿Cuántos días y noches estuvo Jesús en el desierto?", opciones: ["20", "30", "40", "7"], respuesta: "40" },
  { categoria: "Biblia", pregunta: "¿Cómo murió Judas Iscariote?", opciones: ["En la cruz", "Lo apedrearon", "Se ahorcó", "Envenenado"], respuesta: "Se ahorcó" },
  { categoria: "Biblia", pregunta: "¿Quién fue liberado por un ángel de la prisión?", opciones: ["Pedro", "Pablo", "Juan", "Santiago"], respuesta: "Pedro" },
  { categoria: "Biblia", pregunta: "¿Quién fue la mujer que ayudó a los espías en Jericó?", opciones: ["Débora", "Raquel", "Rahab", "Miriam"], respuesta: "Rahab" },
  { categoria: "Biblia", pregunta: "¿Cuál de los apóstoles era pescador junto a su hermano Andrés?", opciones: ["Pedro", "Juan", "Tomás", "Mateo"], respuesta: "Pedro" },
  { categoria: "Biblia", pregunta: "¿Qué profeta fue llevado al cielo en un carro de fuego?", opciones: ["Elías", "Eliseo", "Isaías", "Jeremías"], respuesta: "Elías" },
  { categoria: "Biblia", pregunta: "¿Quién fue el gigante que peleó contra David?", opciones: ["Goliat", "Leviatán", "Filisteo", "Sansón"], respuesta: "Goliat" },
  { categoria: "Biblia", pregunta: "¿Quién fue llamado el 'discípulo amado'?", opciones: ["Pedro", "Juan", "Santiago", "Mateo"], respuesta: "Juan" },
  { categoria: "Biblia", pregunta: "¿En qué río fue bautizado Jesús?", opciones: ["Nilo", "Éufrates", "Tigris", "Jordán"], respuesta: "Jordán" },
  { categoria: "Biblia", pregunta: "¿Qué apóstol escribió el libro de Apocalipsis?", opciones: ["Pedro", "Juan", "Pablo", "Santiago"], respuesta: "Juan" },
  { categoria: "Biblia", pregunta: "¿Quién fue el primer mártir cristiano?", opciones: ["Esteban", "Pablo", "Pedro", "Jacobo"], respuesta: "Esteban" },
  { categoria: "Biblia", pregunta: "¿Qué profeta desafió a los profetas de Baal?", opciones: ["Isaías", "Elías", "Jeremías", "Ezequiel"], respuesta: "Elías" },
  { categoria: "Biblia", pregunta: "¿Qué apóstol escribió la carta a los Romanos?", opciones: ["Pedro", "Pablo", "Juan", "Santiago"], respuesta: "Pablo" },
  { categoria: "Biblia", pregunta: "¿Qué juez de Israel derribó los muros de Jericó?", opciones: ["Débora", "Josué", "Sansón", "Gedeón"], respuesta: "Josué" },
  { categoria: "Biblia", pregunta: "¿Quién fue el discípulo que traicionó a Jesús?", opciones: ["Pedro", "Judas Iscariote", "Tomás", "Juan"], respuesta: "Judas Iscariote" },
  { categoria: "Biblia", pregunta: "¿Qué mujer ungió los pies de Jesús con perfume?", opciones: ["María", "Marta", "María Magdalena", "Sara"], respuesta: "María Magdalena" },
  { categoria: "Biblia", pregunta: "¿Quién fue conocido por su gran fuerza en Israel?", opciones: ["Sansón", "David", "Goliat", "Saúl"], respuesta: "Sansón" },
  { categoria: "Biblia", pregunta: "¿Qué rey escribió muchos proverbios?", opciones: ["Saúl", "David", "Salomón", "Ezequías"], respuesta: "Salomón" },
  { categoria: "Biblia", pregunta: "¿Quién fue conocido por su paciencia, soportando grandes pruebas?", opciones: ["Job", "Moisés", "Abraham", "Isaías"], respuesta: "Job" },
  { categoria: "Biblia", pregunta: "¿Quién fue salvado del horno ardiente junto a sus amigos?", opciones: ["Daniel", "Sadrac, Mesac y Abednego", "José", "Moisés"], respuesta: "Sadrac, Mesac y Abednego" },
  { categoria: "Biblia", pregunta: "¿Qué profeta fue conocido por comer un libro?", opciones: ["Ezequiel", "Jeremías", "Isaías", "Daniel"], respuesta: "Ezequiel" },
  { categoria: "Biblia", pregunta: "¿Qué rey pidió sabiduría a Dios?", opciones: ["David", "Saúl", "Salomón", "Ezequías"], respuesta: "Salomón" },
  { categoria: "Biblia", pregunta: "¿Quién fue padre de Juan el Bautista?", opciones: ["Zacarías", "Simeón", "José", "Simón"], respuesta: "Zacarías" },
  { categoria: "Biblia", pregunta: "¿Quién recibió la visión de la rueda en el cielo?", opciones: ["Ezequiel", "Isaías", "Jeremías", "Daniel"], respuesta: "Ezequiel" },
  { categoria: "Biblia", pregunta: "¿Qué apóstol fue pescador junto a su hermano Andrés?", opciones: ["Pedro", "Juan", "Mateo", "Felipe"], respuesta: "Pedro" },
  { categoria: "Biblia", pregunta: "¿Quién fue liberado por el ángel en la noche?", opciones: ["Pedro", "Juan", "Jacobo", "Pablo"], respuesta: "Pedro" },
  { categoria: "Biblia", pregunta: "¿Qué discípulo caminó sobre el agua?", opciones: ["Pedro", "Tomás", "Juan", "Andrés"], respuesta: "Pedro" },
  { categoria: "Biblia", pregunta: "¿Quién fue vendido por sus hermanos?", opciones: ["José", "Jacob", "Isaac", "Moisés"], respuesta: "José" },
  { categoria: "Biblia", pregunta: "¿Qué apóstol escribió la mayoría de las cartas?", opciones: ["Pedro", "Pablo", "Juan", "Santiago"], respuesta: "Pablo" },
  { categoria: "Biblia", pregunta: "¿Quién fue llamado amigo de Dios?", opciones: ["Moisés", "Abraham", "Isaías", "David"], respuesta: "Abraham" },
  { categoria: "Biblia", pregunta: "¿Quién recibió la visión del fin del mundo?", opciones: ["Juan", "Pedro", "Pablo", "Santiago"], respuesta: "Juan" },
  { categoria: "Biblia", pregunta: "¿Quién fue conocido como el pastor de Israel?", opciones: ["David", "Saúl", "Salomón", "Samuel"], respuesta: "David" },
  { categoria: "Biblia", pregunta: "¿Qué profeta fue conocido por su arco iris?", opciones: ["Noé", "Abraham", "Isaías", "Ezequiel"], respuesta: "Noé" },
  { categoria: "Biblia", pregunta: "¿Quién fue llevado al cielo sin morir?", opciones: ["Enoc", "Moisés", "Elías", "Abraham"], respuesta: "Enoc" },
  { categoria: "Biblia", pregunta: "¿Quién fue conocido por su juicio sabio entre dos madres?", opciones: ["Salomón", "David", "Saúl", "Josué"], respuesta: "Salomón" },
  { categoria: "Biblia", pregunta: "¿Quién fue profeta en Nínive?", opciones: ["Jonás", "Isaías", "Jeremías", "Ezequiel"], respuesta: "Jonás" },
  { categoria: "Biblia", pregunta: "¿Quién fue apedreado por su fe?", opciones: ["Esteban", "Pablo", "Pedro", "Jacobo"], respuesta: "Esteban" },
  { categoria: "Biblia", pregunta: "¿Quién fue conocido por su cabello largo que le daba fuerza?", opciones: ["Sansón", "David", "Goliat", "Saúl"], respuesta: "Sansón" },
  { categoria: "Biblia", pregunta: "¿Quién tuvo sueños que Dios interpretó en Egipto?", opciones: ["José", "Daniel", "Moisés", "Ezequiel"], respuesta: "José" },
  { categoria: "Biblia", pregunta: "¿Quién fue el primer sacerdote de Israel?", opciones: ["Aarón", "Moisés", "Josué", "Elías"], respuesta: "Aarón" },
  { categoria: "Biblia", pregunta: "¿Quién fue el profeta que habló con Dios desde una zarza?", opciones: ["Moisés", "Elías", "Isaías", "Jeremías"], respuesta: "Moisés" },
  { categoria: "Biblia", pregunta: "¿Quién fue el hombre más sabio del Antiguo Testamento?", opciones: ["Salomón", "David", "Abraham", "José"], respuesta: "Salomón" },
  { categoria: "Biblia", pregunta: "¿Quién fue conocido por su fidelidad en Babilonia?", opciones: ["Daniel", "Ezequiel", "Jeremías", "Moisés"], respuesta: "Daniel" },
  { categoria: "Biblia", pregunta: "¿Quién fue visitado por un ángel para anunciar su nacimiento?", opciones: ["María", "Elisabet", "Ana", "Sara"], respuesta: "María" },
  { categoria: "Biblia", pregunta: "¿Qué rey vio un sueño de un gran estatua?", opciones: ["Nabucodonosor", "David", "Salomón", "Saúl"], respuesta: "Nabucodonosor" },
  { categoria: "Biblia", pregunta: "¿Quién fue rescatado del horno ardiente?", opciones: ["Sadrac, Mesac y Abednego", "Daniel", "José", "Ezequiel"], respuesta: "Sadrac, Mesac y Abednego" },
  { categoria: "Biblia", pregunta: "¿Quién escribió el libro de Lamentaciones?", opciones: ["Jeremías", "Isaías", "Ezequiel", "Daniel"], respuesta: "Jeremías" },
  { categoria: "Biblia", pregunta: "¿Quién fue elegido para guiar al pueblo a la Tierra Prometida?", opciones: ["Josué", "Moisés", "David", "Salomón"], respuesta: "Josué" },
  { categoria: "Biblia", pregunta: "¿Quién fue la esposa de Abraham?", opciones: ["Sara", "Rebeca", "Raquel", "Lea"], respuesta: "Sara" },
  { categoria: "Biblia", pregunta: "¿Quién fue el profeta que desafió al rey Acab?", opciones: ["Elías", "Isaías", "Jeremías", "Ezequiel"], respuesta: "Elías" },
  { categoria: "Biblia", pregunta: "¿Quién fue liberado de prisión en la noche por un ángel?", opciones: ["Pedro", "Juan", "Jacobo", "Pablo"], respuesta: "Pedro" },
  { categoria: "Biblia", pregunta: "¿Quién fue conocido como 'varón de Dios' que llamó fuego desde el cielo?", opciones: ["Elías", "Ezequiel", "Isaías", "Jeremías"], respuesta: "Elías" },
  { categoria: "Biblia", pregunta: "¿Quién traicionó a Jesús por 30 piezas de plata?", opciones: ["Judas Iscariote", "Pedro", "Tomás", "Juan"], respuesta: "Judas Iscariote" },
  { categoria: "Biblia", pregunta: "¿Quién fue apedreado por su fe en Jerusalén?", opciones: ["Esteban", "Pablo", "Pedro", "Jacobo"], respuesta: "Esteban" },
  { categoria: "Biblia", pregunta: "¿Quién fue el profeta que anunció el nacimiento de Juan el Bautista?", opciones: ["Zacarías", "Isaías", "Jeremías", "Ezequiel"], respuesta: "Zacarías" },
  { categoria: "Biblia", pregunta: "¿Quién multiplicó los panes y los peces para alimentar a la multitud?", opciones: ["Jesús", "Pedro", "Pablo", "Juan"], respuesta: "Jesús" },
  { categoria: "Biblia", pregunta: "¿Qué discípulo fue llamado 'el incrédulo'?", opciones: ["Tomás", "Pedro", "Juan", "Andrés"], respuesta: "Tomás" },
  { categoria: "Biblia", pregunta: "¿Quién fue salvado de la muerte en el horno ardiente junto a sus amigos?", opciones: ["Sadrac, Mesac y Abednego", "Daniel", "José", "Ezequiel"], respuesta: "Sadrac, Mesac y Abednego" },
  { categoria: "Biblia", pregunta: "¿Quién fue conocido como el amigo de Dios?", opciones: ["Abraham", "Moisés", "Isaías", "David"], respuesta: "Abraham" },
  { categoria: "Biblia", pregunta: "¿Quién escribió la mayoría de los Salmos?", opciones: ["David", "Salomón", "Moisés", "Elías"], respuesta: "David" },
  { categoria: "Biblia", pregunta: "¿Quién fue conocido por su paciencia durante sus pruebas?", opciones: ["Job", "Moisés", "Abraham", "Isaías"], respuesta: "Job" },
  { categoria: "Biblia", pregunta: "¿Qué profeta fue llevado al cielo en un torbellino?", opciones: ["Elías", "Ezequiel", "Isaías", "Jeremías"], respuesta: "Elías" },
  { categoria: "Biblia", pregunta: "¿Quién fue apedreado mientras oraba?", opciones: ["Esteban", "Pablo", "Pedro", "Jacobo"], respuesta: "Esteban" },
  { categoria: "Biblia", pregunta: "¿Quién fue liberado por un ángel de la prisión?", opciones: ["Pedro", "Pablo", "Juan", "Santiago"], respuesta: "Pedro" },
  { categoria: "Biblia", pregunta: "¿Quién recibió la visión del valle de huesos secos?", opciones: ["Ezequiel", "Isaías", "Jeremías", "Daniel"], respuesta: "Ezequiel" },
  { categoria: "Biblia", pregunta: "¿Quién fue el discípulo que negó a Jesús tres veces?", opciones: ["Pedro", "Juan", "Santiago", "Tomás"], respuesta: "Pedro" },
  { categoria: "Biblia", pregunta: "¿Quién interpretó los sueños del faraón?", opciones: ["José", "Daniel", "Moisés", "Ezequiel"], respuesta: "José" },
  { categoria: "Biblia", pregunta: "¿Quién fue conocido por su gran fuerza y cabello largo?", opciones: ["Sansón", "David", "Goliat", "Saúl"], respuesta: "Sansón" },
  { categoria: "Biblia", pregunta: "¿Quién fue bautizado por Juan el Bautista?", opciones: ["Jesús", "Pedro", "Juan", "Pablo"], respuesta: "Jesús" },
  { categoria: "Biblia", pregunta: "¿Quién fue el primer hombre?", opciones: ["Adán", "Noé", "Abraham", "Isaac"], respuesta: "Adán" },
  { categoria: "Biblia", pregunta: "¿Quién fue la primera mujer?", opciones: ["Eva", "Sara", "Rebeca", "Raquel"], respuesta: "Eva" },
  { categoria: "Biblia", pregunta: "¿Quién fue liberado del foso de los leones?", opciones: ["Daniel", "José", "Ezequiel", "Moisés"], respuesta: "Daniel" },
  { categoria: "Biblia", pregunta: "¿Quién fue traicionado por su amigo?", opciones: ["Jesús", "Pedro", "Juan", "Moisés"], respuesta: "Jesús" },
  { categoria: "Biblia", pregunta: "¿Quién recibió los Diez Mandamientos?", opciones: ["Moisés", "Josué", "David", "Salomón"], respuesta: "Moisés" },
  { categoria: "Biblia", pregunta: "¿Quién fue el primer mártir cristiano?", opciones: ["Esteban", "Pablo", "Pedro", "Jacobo"], respuesta: "Esteban" },
  { categoria: "Biblia", pregunta: "¿Qué rey pidió sabiduría a Dios?", opciones: ["Salomón", "David", "Saúl", "Ezequías"], respuesta: "Salomón" },
  { categoria: "Biblia", pregunta: "¿Quién multiplicó los panes y los peces?", opciones: ["Jesús", "Pedro", "Juan", "Pablo"], respuesta: "Jesús" },
  { categoria: "Biblia", pregunta: "¿Quién fue el discípulo amado?", opciones: ["Juan", "Pedro", "Santiago", "Tomás"], respuesta: "Juan" },
  { categoria: "Biblia", pregunta: "¿Quién fue apedreado por su fe?", opciones: ["Esteban", "Pablo", "Pedro", "Jacobo"], respuesta: "Esteban" },
  { categoria: "Biblia", pregunta: "¿Quién fue liberado por un ángel de la prisión?", opciones: ["Pedro", "Pablo", "Juan", "Santiago"], respuesta: "Pedro" },
  { categoria: "Biblia", pregunta: "¿Quién fue conocido por su paciencia?", opciones: ["Job", "Moisés", "Abraham", "Isaías"], respuesta: "Job" },
  { categoria: "Biblia", pregunta: "¿Quién fue llevado al cielo sin morir?", opciones: ["Enoc", "Moisés", "Elías", "Abraham"], respuesta: "Enoc" },
  { categoria: "Biblia", pregunta: "¿Quién interpretó los sueños en Babilonia?", opciones: ["Daniel", "José", "Moisés", "Ezequiel"], respuesta: "Daniel" },
  { categoria: "Biblia", pregunta: "¿Quién traicionó a Jesús por 30 monedas de plata?", opciones: ["Judas Iscariote", "Pedro", "Tomás", "Juan"], respuesta: "Judas Iscariote" },
  { categoria: "Biblia", pregunta: "¿Quién fue el primer rey de Israel?", opciones: ["Saúl", "David", "Salomón", "Josué"], respuesta: "Saúl" },
  { categoria: "Biblia", pregunta: "¿Quién fue liberado del horno ardiente?", opciones: ["Sadrac, Mesac y Abednego", "Daniel", "José", "Ezequiel"], respuesta: "Sadrac, Mesac y Abednego" },
  { categoria: "Biblia", pregunta: "¿Quién fue el profeta que desafió a los profetas de Baal?", opciones: ["Elías", "Isaías", "Jeremías", "Ezequiel"], respuesta: "Elías" }
];
