const preguntasConocimientoUniversal = [
  { categoria: "Conocimiento Universal", pregunta: "¿Cuál es la capital de Francia?", opciones: ["Madrid", "París", "Roma", "Berlín"], respuesta: "París" },
  { categoria: "Conocimiento Universal", pregunta: "¿Cuál es el planeta más grande del sistema solar?", opciones: ["Tierra", "Júpiter", "Saturno", "Marte"], respuesta: "Júpiter" },
  { categoria: "Conocimiento Universal", pregunta: "¿Quién pintó la Mona Lisa?", opciones: ["Pablo Picasso", "Leonardo da Vinci", "Vincent van Gogh", "Miguel Ángel"], respuesta: "Leonardo da Vinci" },
  { categoria: "Conocimiento Universal", pregunta: "¿En qué continente se encuentra Egipto?", opciones: ["Asia", "Europa", "África", "Oceanía"], respuesta: "África" },
  { categoria: "Conocimiento Universal", pregunta: "¿Cuál es el metal más liviano?", opciones: ["Hierro", "Oro", "Litio", "Cobre"], respuesta: "Litio" },
  { categoria: "Conocimiento Universal", pregunta: "¿Qué gas respiran los seres humanos?", opciones: ["Dióxido de carbono", "Oxígeno", "Nitrógeno", "Helio"], respuesta: "Oxígeno" },
  { categoria: "Conocimiento Universal", pregunta: "¿Quién descubrió América?", opciones: ["Cristóbal Colón", "Hernán Cortés", "Marco Polo", "Américo Vespucio"], respuesta: "Cristóbal Colón" },
  { categoria: "Conocimiento Universal", pregunta: "¿Cuál es el océano más grande del mundo?", opciones: ["Atlántico", "Índico", "Ártico", "Pacífico"], respuesta: "Pacífico" },
  { categoria: "Conocimiento Universal", pregunta: "¿Qué científico formuló la teoría de la relatividad?", opciones: ["Isaac Newton", "Albert Einstein", "Galileo Galilei", "Nikola Tesla"], respuesta: "Albert Einstein" },
  { categoria: "Conocimiento Universal", pregunta: "¿Cuál es el país más grande del mundo?", opciones: ["Canadá", "China", "Rusia", "Estados Unidos"], respuesta: "Rusia" },
  { categoria: "Conocimiento Universal", pregunta: "¿Qué instrumento mide la temperatura?", opciones: ["Microscopio", "Telescopio", "Termómetro", "Barómetro"], respuesta: "Termómetro" },
  { categoria: "Conocimiento Universal", pregunta: "¿Cuál es el animal terrestre más rápido?", opciones: ["Tigre", "León", "Guepardo", "Caballo"], respuesta: "Guepardo" },
  { categoria: "Conocimiento Universal", pregunta: "¿Cuántos continentes tiene el planeta Tierra?", opciones: ["5", "6", "7", "8"], respuesta: "7" },
  { categoria: "Conocimiento Universal", pregunta: "¿Cuál es el idioma más hablado del mundo?", opciones: ["Español", "Chino mandarín", "Inglés", "Hindi"], respuesta: "Chino mandarín" },
  { categoria: "Conocimiento Universal", pregunta: "¿Qué parte del cuerpo humano bombea la sangre?", opciones: ["Pulmones", "Hígado", "Corazón", "Cerebro"], respuesta: "Corazón" },
  { categoria: "Conocimiento Universal", pregunta: "¿En qué país se encuentra la Torre Eiffel?", opciones: ["Italia", "Francia", "España", "Alemania"], respuesta: "Francia" },
  { categoria: "Conocimiento Universal", pregunta: "¿Cuál es el desierto más grande del mundo?", opciones: ["Sahara", "Gobi", "Kalahari", "Atacama"], respuesta: "Sahara" },
  { categoria: "Conocimiento Universal", pregunta: "¿Qué planeta es conocido como el planeta rojo?", opciones: ["Venus", "Marte", "Mercurio", "Saturno"], respuesta: "Marte" },
  { categoria: "Conocimiento Universal", pregunta: "¿Quién escribió 'Don Quijote de la Mancha'?", opciones: ["Miguel de Cervantes", "Pablo Neruda", "Gabriel García Márquez", "Mario Vargas Llosa"], respuesta: "Miguel de Cervantes" },
  { categoria: "Conocimiento Universal", pregunta: "¿Qué país tiene forma de bota?", opciones: ["Francia", "España", "Italia", "Grecia"], respuesta: "Italia" },
  { categoria: "Conocimiento Universal", pregunta: "¿En qué continente se encuentra Brasil?", opciones: ["América del Norte", "América del Sur", "Europa", "Oceanía"], respuesta: "América del Sur" },
  { categoria: "Conocimiento Universal", pregunta: "¿Cuál es el río más largo del mundo?", opciones: ["Amazonas", "Nilo", "Yangtsé", "Misisipi"], respuesta: "Nilo" },
  { categoria: "Conocimiento Universal", pregunta: "¿Cuál es la moneda oficial de Japón?", opciones: ["Yen", "Won", "Dólar", "Euro"], respuesta: "Yen" },
  { categoria: "Conocimiento Universal", pregunta: "¿Quién inventó la bombilla eléctrica?", opciones: ["Nikola Tesla", "Thomas Edison", "Benjamin Franklin", "Isaac Newton"], respuesta: "Thomas Edison" },
  { categoria: "Conocimiento Universal", pregunta: "¿Qué planeta está más cerca del Sol?", opciones: ["Venus", "Mercurio", "Tierra", "Marte"], respuesta: "Mercurio" },
  { categoria: "Conocimiento Universal", pregunta: "¿Cuántos huesos tiene el cuerpo humano adulto?", opciones: ["106", "206", "300", "150"], respuesta: "206" },
  { categoria: "Conocimiento Universal", pregunta: "¿Cuál es el animal más grande del mundo?", opciones: ["Elefante", "Ballena azul", "Jirafa", "Tiburón blanco"], respuesta: "Ballena azul" },
  { categoria: "Conocimiento Universal", pregunta: "¿Quién fue el primer hombre en pisar la Luna?", opciones: ["Neil Armstrong", "Buzz Aldrin", "Yuri Gagarin", "Alan Shepard"], respuesta: "Neil Armstrong" },
  { categoria: "Conocimiento Universal", pregunta: "¿Qué gas necesitan las plantas para realizar la fotosíntesis?", opciones: ["Oxígeno", "Hidrógeno", "Dióxido de carbono", "Nitrógeno"], respuesta: "Dióxido de carbono" },
  { categoria: "Conocimiento Universal", pregunta: "¿En qué país se encuentran las pirámides de Giza?", opciones: ["México", "Egipto", "India", "Irán"], respuesta: "Egipto" },
  { categoria: "Conocimiento Universal", pregunta: "¿Cuál es el inventor del teléfono?", opciones: ["Thomas Edison", "Alexander Graham Bell", "Nikola Tesla", "Henry Ford"], respuesta: "Alexander Graham Bell" },
  { categoria: "Conocimiento Universal", pregunta: "¿Cuántos planetas hay en el sistema solar?", opciones: ["7", "8", "9", "10"], respuesta: "8" },
  { categoria: "Conocimiento Universal", pregunta: "¿En qué año comenzó la Segunda Guerra Mundial?", opciones: ["1914", "1939", "1945", "1920"], respuesta: "1939" },
  { categoria: "Conocimiento Universal", pregunta: "¿Cuál es la capital de México?", opciones: ["Guadalajara", "Ciudad de México", "Cancún", "Monterrey"], respuesta: "Ciudad de México" },
  { categoria: "Conocimiento Universal", pregunta: "¿Quién formuló las leyes del movimiento?", opciones: ["Einstein", "Newton", "Galileo", "Kepler"], respuesta: "Newton" },
  { categoria: "Conocimiento Universal", pregunta: "¿Cuál es el idioma oficial de Brasil?", opciones: ["Español", "Portugués", "Inglés", "Francés"], respuesta: "Portugués" },
  { categoria: "Conocimiento Universal", pregunta: "¿Qué océano baña las costas de Chile?", opciones: ["Atlántico", "Pacífico", "Índico", "Ártico"], respuesta: "Pacífico" },
  { categoria: "Conocimiento Universal", pregunta: "¿Quién fue el primer presidente de Estados Unidos?", opciones: ["Abraham Lincoln", "George Washington", "John Adams", "Thomas Jefferson"], respuesta: "George Washington" },
  { categoria: "Conocimiento Universal", pregunta: "¿Cuál es el continente más pequeño?", opciones: ["Oceanía", "Europa", "América", "África"], respuesta: "Oceanía" },
  { categoria: "Conocimiento Universal", pregunta: "¿Qué elemento químico tiene el símbolo O?", opciones: ["Oro", "Oxígeno", "Osmio", "Onio"], respuesta: "Oxígeno" },
  { categoria: "Conocimiento Universal", pregunta: "¿Qué país tiene más habitantes del mundo?", opciones: ["China", "India", "Estados Unidos", "Rusia"], respuesta: "India" },
  { categoria: "Conocimiento Universal", pregunta: "¿Cuál es el animal nacional de Australia?", opciones: ["Canguro", "Koala", "Emú", "Dingo"], respuesta: "Canguro" },
  { categoria: "Conocimiento Universal", pregunta: "¿En qué año llegó el hombre a la Luna?", opciones: ["1965", "1969", "1972", "1980"], respuesta: "1969" },
  { categoria: "Conocimiento Universal", pregunta: "¿Qué país inventó la pólvora?", opciones: ["Japón", "China", "India", "Alemania"], respuesta: "China" },
  { categoria: "Conocimiento Universal", pregunta: "¿Cuál es el océano más profundo del planeta?", opciones: ["Atlántico", "Índico", "Pacífico", "Ártico"], respuesta: "Pacífico" },
  { categoria: "Conocimiento Universal", pregunta: "¿Qué parte del cuerpo controla el equilibrio?", opciones: ["Oído interno", "Cerebro", "Corazón", "Hígado"], respuesta: "Oído interno" },
  { categoria: "Conocimiento Universal", pregunta: "¿Cuál es el metal más caro del mundo?", opciones: ["Oro", "Platino", "Rodio", "Plata"], respuesta: "Rodio" },
  { categoria: "Conocimiento Universal", pregunta: "¿En qué país se encuentra el Monte Everest?", opciones: ["India", "China", "Nepal", "Bután"], respuesta: "Nepal" },
  { categoria: "Conocimiento Universal", pregunta: "¿Qué científico propuso la teoría heliocéntrica?", opciones: ["Copérnico", "Galileo", "Kepler", "Newton"], respuesta: "Copérnico" },
  { categoria: "Conocimiento Universal", pregunta: "¿Cuál es el planeta más cercano a la Tierra?", opciones: ["Venus", "Marte", "Júpiter", "Saturno"], respuesta: "Venus" },
  { categoria: "Conocimiento Universal", pregunta: "¿Cuál es el animal más inteligente después del humano?", opciones: ["Perro", "Delfín", "Gorila", "Elefante"], respuesta: "Delfín" },
  { categoria: "Conocimiento Universal", pregunta: "¿Qué país es famoso por la Torre de Pisa?", opciones: ["Francia", "Italia", "España", "Portugal"], respuesta: "Italia" },
  { categoria: "Conocimiento Universal", pregunta: "¿Cuál es el inventor del avión?", opciones: ["Nikola Tesla", "Hermanos Wright", "Henry Ford", "Alexander Fleming"], respuesta: "Hermanos Wright" },
  { categoria: "Conocimiento Universal", pregunta: "¿En qué país se encuentra la Muralla China?", opciones: ["China", "Japón", "Corea del Sur", "Vietnam"], respuesta: "China" },
  { categoria: "Conocimiento Universal", pregunta: "¿Qué país tiene forma de bota?", opciones: ["Italia", "España", "Francia", "Portugal"], respuesta: "Italia" },
  { categoria: "Conocimiento Universal", pregunta: "¿Cuál es el hueso más largo del cuerpo humano?", opciones: ["Fémur", "Tibia", "Radio", "Húmero"], respuesta: "Fémur" },
  { categoria: "Conocimiento Universal", pregunta: "¿Qué océano está entre África y Australia?", opciones: ["Índico", "Atlántico", "Pacífico", "Ártico"], respuesta: "Índico" },
  { categoria: "Conocimiento Universal", pregunta: "¿Qué país tiene como símbolo el dragón?", opciones: ["Japón", "China", "Corea del Sur", "Vietnam"], respuesta: "China" },
  { categoria: "Conocimiento Universal", pregunta: "¿Qué científico descubrió la penicilina?", opciones: ["Louis Pasteur", "Alexander Fleming", "Isaac Newton", "Galileo Galilei"], respuesta: "Alexander Fleming" },
  { categoria: "Conocimiento Universal", pregunta: "¿Cuál es el símbolo químico del agua?", opciones: ["CO2", "O2", "H2O", "NaCl"], respuesta: "H2O" },
  { categoria: "Conocimiento Universal", pregunta: "¿Qué planeta tiene anillos visibles?", opciones: ["Urano", "Neptuno", "Saturno", "Júpiter"], respuesta: "Saturno" },
  { categoria: "Conocimiento Universal", pregunta: "¿Cuál es el continente con más países?", opciones: ["África", "Asia", "Europa", "América"], respuesta: "África" },
  { categoria: "Conocimiento Universal", pregunta: "¿Qué país es conocido como la tierra del sol naciente?", opciones: ["China", "Corea del Sur", "Japón", "Tailandia"], respuesta: "Japón" }
];
