const preguntasHistoriaRD = [
  // 1-10
  { categoria: "Historia RD", pregunta: "¿En qué año se proclamó la independencia de la República Dominicana?", opciones: ["1844", "1865", "1821", "1924"], respuesta: "1844" },
  { categoria: "Historia RD", pregunta: "¿Quién fue el principal líder de la independencia dominicana?", opciones: ["Juan Pablo Duarte", "Gregorio Luperón", "Francisco del Rosario Sánchez", "Pedro Santana"], respuesta: "Juan Pablo Duarte" },
  { categoria: "Historia RD", pregunta: "¿Qué país ocupó la República Dominicana antes de su independencia?", opciones: ["Haití", "España", "Francia", "Inglaterra"], respuesta: "Haití" },
  { categoria: "Historia RD", pregunta: "¿Quién fue el primer presidente de la República Dominicana?", opciones: ["Pedro Santana", "Buenaventura Báez", "José Núñez de Cáceres", "Francisco del Rosario Sánchez"], respuesta: "Pedro Santana" },
  { categoria: "Historia RD", pregunta: "¿Qué guerra marcó la independencia de la República Dominicana en 1844?", opciones: ["Guerra de Independencia", "Guerra de Restauración", "Guerra Civil", "Guerra del 30"], respuesta: "Guerra de Independencia" },
  { categoria: "Historia RD", pregunta: "¿Qué poeta dominicano escribió 'Canto a la Patria'?", opciones: ["Salomé Ureña", "Juan Bosch", "Pedro Mir", "Emilio Prud’Homme"], respuesta: "Emilio Prud’Homme" },
  { categoria: "Historia RD", pregunta: "¿En qué año terminó la Guerra de Restauración?", opciones: ["1865", "1844", "1870", "1855"], respuesta: "1865" },
  { categoria: "Historia RD", pregunta: "¿Quién lideró la Guerra de Restauración contra España?", opciones: ["Gregorio Luperón", "Pedro Santana", "Juan Pablo Duarte", "Francisco del Rosario Sánchez"], respuesta: "Gregorio Luperón" },
  { categoria: "Historia RD", pregunta: "¿Qué ciudad fue la primera capital de la República Dominicana?", opciones: ["Santo Domingo", "Santiago de los Caballeros", "Puerto Plata", "La Vega"], respuesta: "Santo Domingo" },
  { categoria: "Historia RD", pregunta: "¿Cuál de estos presidentes fue un escritor y político destacado?", opciones: ["Juan Bosch", "Pedro Santana", "Buenaventura Báez", "Horacio Vásquez"], respuesta: "Juan Bosch" },

  // 11-20
  { categoria: "Historia RD", pregunta: "¿En qué año se produjo la anexión a España?", opciones: ["1861", "1844", "1870", "1855"], respuesta: "1861" },
  { categoria: "Historia RD", pregunta: "¿Qué líder dominicano luchó contra la anexión a España?", opciones: ["Gregorio Luperón", "Pedro Santana", "Juan Pablo Duarte", "Francisco del Rosario Sánchez"], respuesta: "Gregorio Luperón" },
  { categoria: "Historia RD", pregunta: "¿Quién proclamó la independencia efímera de 1821?", opciones: ["José Núñez de Cáceres", "Juan Pablo Duarte", "Pedro Santana", "Buenaventura Báez"], respuesta: "José Núñez de Cáceres" },
  { categoria: "Historia RD", pregunta: "¿Cuál fue la primera Constitución dominicana?", opciones: ["Constitución de 1844", "Constitución de 1865", "Constitución de 1907", "Constitución de 1854"], respuesta: "Constitución de 1844" },
  { categoria: "Historia RD", pregunta: "¿Qué presidente dominicano fue derrocado en 1930?", opciones: ["Horacio Vásquez", "Rafael Trujillo", "Juan Bosch", "Pedro Santana"], respuesta: "Horacio Vásquez" },
  { categoria: "Historia RD", pregunta: "¿En qué año inició la dictadura de Rafael Trujillo?", opciones: ["1930", "1924", "1945", "1916"], respuesta: "1930" },
  { categoria: "Historia RD", pregunta: "¿Qué evento mundial coincidió con la ocupación estadounidense en RD?", opciones: ["Primera Guerra Mundial", "Segunda Guerra Mundial", "Guerra Civil Española", "Guerra de Vietnam"], respuesta: "Primera Guerra Mundial" },
  { categoria: "Historia RD", pregunta: "¿Qué presidente dominicano fundó el Partido Revolucionario Dominicano (PRD)?", opciones: ["Juan Bosch", "Pedro Santana", "Rafael Trujillo", "Horacio Vásquez"], respuesta: "Juan Bosch" },
  { categoria: "Historia RD", pregunta: "¿Qué guerra tuvo lugar entre 1916 y 1924?", opciones: ["Ocupación estadounidense", "Guerra de Restauración", "Guerra Civil", "Guerra de Independencia"], respuesta: "Ocupación estadounidense" },
  { categoria: "Historia RD", pregunta: "¿Qué presidente dominicano implementó reformas educativas importantes en 1963?", opciones: ["Juan Bosch", "Rafael Trujillo", "Horacio Vásquez", "Leonel Fernández"], respuesta: "Juan Bosch" },

  // 21-30
  { categoria: "Historia RD", pregunta: "¿Cuál es el nombre del himno nacional dominicano?", opciones: ["Himno Nacional", "Canto a la Patria", "Himno de Duarte", "Gloria al Bravo Pueblo"], respuesta: "Himno Nacional" },
  { categoria: "Historia RD", pregunta: "¿Quién es considerado el Padre de la Patria?", opciones: ["Juan Pablo Duarte", "Francisco del Rosario Sánchez", "Ramón Matías Mella", "Pedro Santana"], respuesta: "Juan Pablo Duarte" },
  { categoria: "Historia RD", pregunta: "¿Qué líder dominicano participó en la independencia de Haití?", opciones: ["José Núñez de Cáceres", "Juan Pablo Duarte", "Pedro Santana", "Ramón Matías Mella"], respuesta: "José Núñez de Cáceres" },
  { categoria: "Historia RD", pregunta: "¿Cuál es el año de nacimiento de Juan Pablo Duarte?", opciones: ["1813", "1821", "1808", "1830"], respuesta: "1813" },
  { categoria: "Historia RD", pregunta: "¿Qué batalla selló la independencia de 1844?", opciones: ["Batalla del 19 de Marzo", "Batalla de Azua", "Batalla de Santiago", "Batalla de Beler"], respuesta: "Batalla de Azua" },
  { categoria: "Historia RD", pregunta: "¿Quién fue el presidente durante la Guerra de 1916?", opciones: ["Eladio Victoria", "Horacio Vásquez", "Juan Bosch", "Pedro Santana"], respuesta: "Eladio Victoria" },
  { categoria: "Historia RD", pregunta: "¿Qué país ocupó RD entre 1916 y 1924?", opciones: ["Estados Unidos", "Haití", "España", "Francia"], respuesta: "Estados Unidos" },
  { categoria: "Historia RD", pregunta: "¿Qué presidente dominicano fue derrocado por un golpe en 1963?", opciones: ["Juan Bosch", "Rafael Trujillo", "Horacio Vásquez", "Leonel Fernández"], respuesta: "Juan Bosch" },
  { categoria: "Historia RD", pregunta: "¿Qué líder dominicano proclamó la independencia de la anexión a España en 1865?", opciones: ["Gregorio Luperón", "Pedro Santana", "Juan Pablo Duarte", "Francisco del Rosario Sánchez"], respuesta: "Gregorio Luperón" },
  { categoria: "Historia RD", pregunta: "¿Quién lideró la revolución de abril de 1965?", opciones: ["Francisco Caamaño", "Juan Bosch", "Rafael Trujillo", "Horacio Vásquez"], respuesta: "Francisco Caamaño" },

  // 31-40
  { categoria: "Historia RD", pregunta: "¿Cuál fue la primera capital colonial?", opciones: ["Santo Domingo", "Santiago de los Caballeros", "La Vega", "Puerto Plata"], respuesta: "Santo Domingo" },
  { categoria: "Historia RD", pregunta: "¿Qué mar baña las costas de la República Dominicana?", opciones: ["Mar Caribe", "Océano Atlántico", "Mar Mediterráneo", "Mar del Norte"], respuesta: "Mar Caribe" },
  { categoria: "Historia RD", pregunta: "¿Quién proclamó la independencia de Haití y dejó libre a RD?", opciones: ["Jean-Pierre Boyer", "Toussaint Louverture", "Henri Christophe", "Alexandre Pétion"], respuesta: "Jean-Pierre Boyer" },
  { categoria: "Historia RD", pregunta: "¿Qué presidente dominicano tuvo un largo mandato desde 1930 hasta 1961?", opciones: ["Rafael Trujillo", "Juan Bosch", "Horacio Vásquez", "Pedro Santana"], respuesta: "Rafael Trujillo" },
  { categoria: "Historia RD", pregunta: "¿Cuál es la montaña más alta de RD?", opciones: ["Pico Duarte", "Pico Isabel de Torres", "Loma Quita Espuela", "Pico Diego de Ocampo"], respuesta: "Pico Duarte" },
  { categoria: "Historia RD", pregunta: "¿En qué año terminó la dictadura de Trujillo?", opciones: ["1961", "1965", "1950", "1945"], respuesta: "1961" },
  { categoria: "Historia RD", pregunta: "¿Qué presidente dominicano implementó la reforma agraria?", opciones: ["Juan Bosch", "Leonel Fernández", "Rafael Trujillo", "Horacio Vásquez"], respuesta: "Juan Bosch" },
  { categoria: "Historia RD", pregunta: "¿Qué movimiento político dominicano fundó Juan Bosch?", opciones: ["PRD", "PLD", "PRM", "FP"], respuesta: "PRD" },
  { categoria: "Historia RD", pregunta: "¿Quién lideró la invasión militar de RD en 1965?", opciones: ["Estados Unidos", "Cuba", "Haití", "España"], respuesta: "Estados Unidos" },
  { categoria: "Historia RD", pregunta: "¿Qué batalla marcó el fin de la Guerra de Independencia de 1844?", opciones: ["Batalla del 19 de Marzo", "Batalla de Azua", "Batalla de Santiago", "Batalla de Beler"], respuesta: "Batalla de Azua" },

  // 41-50
  { categoria: "Historia RD", pregunta: "¿Qué poeta dominicano escribió 'Canto a la Patria'?", opciones: ["Emilio Prud’Homme", "Salomé Ureña", "Pedro Mir", "Juan Bosch"], respuesta: "Emilio Prud’Homme" },
  { categoria: "Historia RD", pregunta: "¿Qué presidente fue asesinado en 1963?", opciones: ["Juan Bosch", "Rafael Trujillo", "Horacio Vásquez", "Pedro Santana"], respuesta: "Juan Bosch" },
  { categoria: "Historia RD", pregunta: "¿Qué presidente dominicano fundó el PLD?", opciones: ["Juan Bosch", "Leonel Fernández", "Rafael Trujillo", "Pedro Santana"], respuesta: "Juan Bosch" },
  { categoria: "Historia RD", pregunta: "¿Qué guerra ocurrió entre 1916 y 1924?", opciones: ["Ocupación estadounidense", "Guerra de Restauración", "Guerra Civil", "Guerra de Independencia"], respuesta: "Ocupación estadounidense" },
  { categoria: "Historia RD", pregunta: "¿Quién fue el dictador antes de la muerte de Trujillo?", opciones: ["Rafael Trujillo", "Pedro Santana", "Horacio Vásquez", "Juan Bosch"], respuesta: "Rafael Trujillo" },
  { categoria: "Historia RD", pregunta: "¿Qué presidente modernizó la educación en 1963?", opciones: ["Juan Bosch", "Leonel Fernández", "Rafael Trujillo", "Horacio Vásquez"], respuesta: "Juan Bosch" },
  { categoria: "Historia RD", pregunta: "¿Qué líder dominicano participó en la independencia de 1844?", opciones: ["Juan Pablo Duarte", "Pedro Santana", "Buenaventura Báez", "Ramón Matías Mella"], respuesta: "Juan Pablo Duarte" },
  { categoria: "Historia RD", pregunta: "¿Qué evento internacional afectó la ocupación estadounidense?", opciones: ["Primera Guerra Mundial", "Segunda Guerra Mundial", "Guerra Fría", "Revolución Francesa"], respuesta: "Primera Guerra Mundial" },
  { categoria: "Historia RD", pregunta: "¿Qué líder participó en la anexión a España?", opciones: ["Pedro Santana", "Juan Pablo Duarte", "Francisco del Rosario Sánchez", "Gregorio Luperón"], respuesta: "Pedro Santana" },
  { categoria: "Historia RD", pregunta: "¿Qué presidente dominicano luchó contra la corrupción en los años 60?", opciones: ["Juan Bosch", "Rafael Trujillo", "Horacio Vásquez", "Pedro Santana"], respuesta: "Juan Bosch" },

  // 51-60
  { categoria: "Historia RD", pregunta: "¿Cuál fue el principal puerto colonial?", opciones: ["Santo Domingo", "Puerto Plata", "Santiago", "La Vega"], respuesta: "Santo Domingo" },
  { categoria: "Historia RD", pregunta: "¿Quién fue el primer presidente tras la ocupación estadounidense?", opciones: ["Horacio Vásquez", "Juan Bosch", "Pedro Santana", "Rafael Trujillo"], respuesta: "Horacio Vásquez" },
  { categoria: "Historia RD", pregunta: "¿En qué año se firmó la Constitución de 1963?", opciones: ["1963", "1844", "1865", "1930"], respuesta: "1963" },
  { categoria: "Historia RD", pregunta: "¿Qué presidente fue derrocado por un golpe militar en 1963?", opciones: ["Juan Bosch", "Pedro Santana", "Horacio Vásquez", "Rafael Trujillo"], respuesta: "Juan Bosch" },
  { categoria: "Historia RD", pregunta: "¿Qué guerra restauró la independencia tras la anexión a España?", opciones: ["Guerra de Restauración", "Guerra de Independencia", "Guerra Civil", "Guerra del 30"], respuesta: "Guerra de Restauración" },
  { categoria: "Historia RD", pregunta: "¿Qué presidente lideró la economía durante los años 80?", opciones: ["Salvador Jorge Blanco", "Juan Bosch", "Leonel Fernández", "Rafael Trujillo"], respuesta: "Salvador Jorge Blanco" },
  { categoria: "Historia RD", pregunta: "¿Quién fue el líder del PRD tras la dictadura?", opciones: ["José Francisco Peña Gómez", "Juan Bosch", "Leonel Fernández", "Rafael Trujillo"], respuesta: "José Francisco Peña Gómez" },
  { categoria: "Historia RD", pregunta: "¿Qué ciudad es conocida como la 'Ciudad Corazón de la República Dominicana'?", opciones: ["Santiago de los Caballeros", "Santo Domingo", "La Vega", "Puerto Plata"], respuesta: "Santiago de los Caballeros" },
  { categoria: "Historia RD", pregunta: "¿Qué presidente implementó el Plan de Seguridad Social?", opciones: ["Leonel Fernández", "Juan Bosch", "Rafael Trujillo", "Horacio Vásquez"], respuesta: "Leonel Fernández" },
  { categoria: "Historia RD", pregunta: "¿Qué líder dominicano fue exiliado durante la dictadura?", opciones: ["Juan Bosch", "Pedro Santana", "Horacio Vásquez", "Rafael Trujillo"], respuesta: "Juan Bosch" },

  // 61-70
  { categoria: "Historia RD", pregunta: "¿Cuál fue el primer periódico dominicano?", opciones: ["El Telégrafo", "Listín Diario", "El Caribe", "El Nacional"], respuesta: "El Telégrafo" },
  { categoria: "Historia RD", pregunta: "¿Quién fue el primer embajador dominicano en EE.UU.?", opciones: ["Juan Bautista Vicini", "Pedro Santana", "Buenaventura Báez", "Juan Pablo Duarte"], respuesta: "Juan Bautista Vicini" },
  { categoria: "Historia RD", pregunta: "¿Qué presidente dominicano promovió la educación técnica?", opciones: ["Leonel Fernández", "Juan Bosch", "Rafael Trujillo", "Horacio Vásquez"], respuesta: "Leonel Fernández" },
  { categoria: "Historia RD", pregunta: "¿Qué tratado resolvió la frontera con Haití?", opciones: ["Tratado de 1936", "Tratado de París", "Tratado de 1929", "Tratado de 1844"], respuesta: "Tratado de 1936" },
  { categoria: "Historia RD", pregunta: "¿Quién fue el primer ministro de economía dominicano?", opciones: ["Manuel A. Ureña", "Pedro Santana", "Juan Bosch", "Horacio Vásquez"], respuesta: "Manuel A. Ureña" },
  { categoria: "Historia RD", pregunta: "¿Qué presidente promovió la industrialización en los 70s?", opciones: ["Joaquín Balaguer", "Juan Bosch", "Leonel Fernández", "Rafael Trujillo"], respuesta: "Joaquín Balaguer" },
  { categoria: "Historia RD", pregunta: "¿Qué dictador fue asesinado en 1961?", opciones: ["Rafael Trujillo", "Pedro Santana", "Horacio Vásquez", "Juan Bosch"], respuesta: "Rafael Trujillo" },
  { categoria: "Historia RD", pregunta: "¿Quién lideró la resistencia contra la ocupación estadounidense?", opciones: ["Francisco Henríquez y Carvajal", "Juan Bosch", "Pedro Santana", "Horacio Vásquez"], respuesta: "Francisco Henríquez y Carvajal" },
  { categoria: "Historia RD", pregunta: "¿Qué evento internacional influenció la política dominicana en 1965?", opciones: ["Guerra Fría", "Segunda Guerra Mundial", "Primera Guerra Mundial", "Revolución Cubana"], respuesta: "Guerra Fría" },
  { categoria: "Historia RD", pregunta: "¿Quién fue presidente después de la muerte de Trujillo?", opciones: ["Joaquín Balaguer", "Juan Bosch", "Horacio Vásquez", "Pedro Santana"], respuesta: "Joaquín Balaguer" },

  // 71-80
  { categoria: "Historia RD", pregunta: "¿Qué presidente dominicano promovió la Constitución de 2010?", opciones: ["Leonel Fernández", "Danilo Medina", "Joaquín Balaguer", "Hipólito Mejía"], respuesta: "Leonel Fernández" },
  { categoria: "Historia RD", pregunta: "¿Qué presidente dominicano fundó el PLD en 1973?", opciones: ["Juan Bosch", "Leonel Fernández", "Joaquín Balaguer", "Hipólito Mejía"], respuesta: "Juan Bosch" },
  { categoria: "Historia RD", pregunta: "¿Qué evento internacional afectó a RD en 1916?", opciones: ["Ocupación estadounidense", "Primera Guerra Mundial", "Segunda Guerra Mundial", "Revolución Cubana"], respuesta: "Ocupación estadounidense" },
  { categoria: "Historia RD", pregunta: "¿Quién fue presidente durante la construcción del Metro de Santo Domingo?", opciones: ["Leonel Fernández", "Hipólito Mejía", "Danilo Medina", "Joaquín Balaguer"], respuesta: "Leonel Fernández" },
  { categoria: "Historia RD", pregunta: "¿Qué líder dominicano fundó el PRSC?", opciones: ["Joaquín Balaguer", "Juan Bosch", "Leonel Fernández", "Hipólito Mejía"], respuesta: "Joaquín Balaguer" },
  { categoria: "Historia RD", pregunta: "¿Cuál fue el primer aeropuerto internacional dominicano?", opciones: ["La Isabela", "Las Américas", "Cibao", "Puerto Plata"], respuesta: "La Isabela" },
  { categoria: "Historia RD", pregunta: "¿Qué presidente dominicano promovió la reforma judicial en los 90s?", opciones: ["Leonel Fernández", "Joaquín Balaguer", "Hipólito Mejía", "Juan Bosch"], respuesta: "Leonel Fernández" },
  { categoria: "Historia RD", pregunta: "¿Qué líder dominicano participó en la fundación de la OEA?", opciones: ["Rafael Trujillo", "Juan Bosch", "Joaquín Balaguer", "Horacio Vásquez"], respuesta: "Juan Bosch" },
  { categoria: "Historia RD", pregunta: "¿Cuál fue la primera universidad dominicana?", opciones: ["Universidad Autónoma de Santo Domingo", "Pontificia Universidad Católica", "Universidad Iberoamericana", "Universidad APEC"], respuesta: "Universidad Autónoma de Santo Domingo" },
  { categoria: "Historia RD", pregunta: "¿Quién lideró la Junta Revolucionaria de 1961?", opciones: ["Juan Bosch", "Joaquín Balaguer", "Ramón Cáceres", "Francisco Caamaño"], respuesta: "Juan Bosch" },

  // 81-90
  { categoria: "Historia RD", pregunta: "¿Qué presidente dominicano implementó la Tanda Extendida en educación?", opciones: ["Leonel Fernández", "Hipólito Mejía", "Danilo Medina", "Joaquín Balaguer"], respuesta: "Danilo Medina" },
  { categoria: "Historia RD", pregunta: "¿Qué líder dominicano fue presidente provisional en 1965?", opciones: ["Francisco Caamaño", "Juan Bosch", "Horacio Vásquez", "Joaquín Balaguer"], respuesta: "Francisco Caamaño" },
  { categoria: "Historia RD", pregunta: "¿Cuál fue la primera emisora de radio dominicana?", opciones: ["HIN Radio", "Radio Televisión Dominicana", "La Voz del Trópico", "Radio Santo Domingo"], respuesta: "HIN Radio" },
  { categoria: "Historia RD", pregunta: "¿Qué evento internacional influyó en la invasión estadounidense de 1965?", opciones: ["Guerra Fría", "Primera Guerra Mundial", "Segunda Guerra Mundial", "Guerra de Corea"], respuesta: "Guerra Fría" },
  { categoria: "Historia RD", pregunta: "¿Qué presidente dominicano promovió el turismo en los 70s?", opciones: ["Joaquín Balaguer", "Juan Bosch", "Leonel Fernández", "Hipólito Mejía"], respuesta: "Joaquín Balaguer" },
  { categoria: "Historia RD", pregunta: "¿Quién fundó el Banco Central de la República Dominicana?", opciones: ["Pedro Henríquez Ureña", "Joaquín Balaguer", "Juan Bosch", "Horacio Vásquez"], respuesta: "Joaquín Balaguer" },
  { categoria: "Historia RD", pregunta: "¿Qué líder dominicano fue presidente tras la ocupación de 1916?", opciones: ["Horacio Vásquez", "Juan Bosch", "Pedro Santana", "Joaquín Balaguer"], respuesta: "Horacio Vásquez" },
  { categoria: "Historia RD", pregunta: "¿Cuál fue el primer canal de televisión dominicano?", opciones: ["Color Visión", "Teleantillas", "Telemicro", "CERTV"], respuesta: "Color Visión" },
  { categoria: "Historia RD", pregunta: "¿Qué presidente dominicano creó la Comisión Nacional de Energía?", opciones: ["Leonel Fernández", "Hipólito Mejía", "Joaquín Balaguer", "Danilo Medina"], respuesta: "Leonel Fernández" },
  { categoria: "Historia RD", pregunta: "¿Qué presidente dominicano promovió la modernización del transporte público?", opciones: ["Leonel Fernández", "Hipólito Mejía", "Danilo Medina", "Joaquín Balaguer"], respuesta: "Leonel Fernández" },

  // 91-100
  { categoria: "Historia RD", pregunta: "¿Quién fue presidente durante la creación del Plan Nacional de Vivienda?", opciones: ["Danilo Medina", "Leonel Fernández", "Hipólito Mejía", "Joaquín Balaguer"], respuesta: "Danilo Medina" },
  { categoria: "Historia RD", pregunta: "¿Qué presidente dominicano promovió la Reforma Fiscal en los 90s?", opciones: ["Leonel Fernández", "Hipólito Mejía", "Danilo Medina", "Joaquín Balaguer"], respuesta: "Leonel Fernández" },
  { categoria: "Historia RD", pregunta: "¿Quién fue el líder del PRSC tras la muerte de Balaguer?", opciones: ["Carlos Morales Troncoso", "Juan Bosch", "Leonel Fernández", "Hipólito Mejía"], respuesta: "Carlos Morales Troncoso" },
  { categoria: "Historia RD", pregunta: "¿Qué presidente dominicano promovió el turismo sostenible en 2000s?", opciones: ["Hipólito Mejía", "Leonel Fernández", "Danilo Medina", "Joaquín Balaguer"], respuesta: "Leonel Fernández" },
  { categoria: "Historia RD", pregunta: "¿Qué presidente dominicano impulsó el Metro de Santo Domingo?", opciones: ["Leonel Fernández", "Hipólito Mejía", "Danilo Medina", "Joaquín Balaguer"], respuesta: "Leonel Fernández" },
  { categoria: "Historia RD", pregunta: "¿Quién fue presidente durante el auge económico de 2005?", opciones: ["Leonel Fernández", "Hipólito Mejía", "Danilo Medina", "Joaquín Balaguer"], respuesta: "Leonel Fernández" },
  { categoria: "Historia RD", pregunta: "¿Qué líder dominicano fundó el Partido Reformista Social Cristiano (PRSC)?", opciones: ["Joaquín Balaguer", "Juan Bosch", "Leonel Fernández", "Hipólito Mejía"], respuesta: "Joaquín Balaguer" },
  { categoria: "Historia RD", pregunta: "¿Qué presidente dominicano fue exiliado por el golpe de 1963?", opciones: ["Juan Bosch", "Joaquín Balaguer", "Leonel Fernández", "Hipólito Mejía"], respuesta: "Juan Bosch" },
  { categoria: "Historia RD", pregunta: "¿Qué presidente dominicano promovió la Ley de Función Pública?", opciones: ["Leonel Fernández", "Hipólito Mejía", "Danilo Medina", "Joaquín Balaguer"], respuesta: "Leonel Fernández" },
  { categoria: "Historia RD", pregunta: "¿Qué líder dominicano fue parte de la Revolución de Abril de 1965?", opciones: ["Francisco Caamaño", "Juan Bosch", "Horacio Vásquez", "Joaquín Balaguer"], respuesta: "Francisco Caamaño" }
];
