const preguntasItaliano = [
  { categoria: "Italiano", pregunta: "¿Cómo se dice 'Hola' en italiano?", opciones: ["Ciao", "Hello", "Hola", "Salut"], respuesta: "Ciao" },
  { categoria: "Italiano", pregunta: "¿Cómo se dice 'Gracias' en italiano?", opciones: ["Grazie", "Thank you", "Merci", "Gracias"], respuesta: "Grazie" },
  { categoria: "Italiano", pregunta: "¿Cómo se dice 'Adiós' en italiano?", opciones: ["Arrivederci", "Goodbye", "Adiós", "Au revoir"], respuesta: "Arrivederci" },
  { categoria: "Italiano", pregunta: "¿Cómo se dice 'Por favor' en italiano?", opciones: ["Per favore", "Please", "Por favor", "S'il vous plaît"], respuesta: "Per favore" },
  { categoria: "Italiano", pregunta: "¿Cómo se dice 'Lo siento' en italiano?", opciones: ["Mi dispiace", "Sorry", "Lo siento", "Désolé"], respuesta: "Mi dispiace" },
  { categoria: "Italiano", pregunta: "¿Cómo se dice 'Sí' en italiano?", opciones: ["Sì", "Yes", "Oui", "Sí"], respuesta: "Sì" },
  { categoria: "Italiano", pregunta: "¿Cómo se dice 'No' en italiano?", opciones: ["No", "No", "Non", "Nein"], respuesta: "No" },
  { categoria: "Italiano", pregunta: "¿Cómo se dice 'Amigo' en italiano?", opciones: ["Amico", "Friend", "Ami", "Amigo"], respuesta: "Amico" },
  { categoria: "Italiano", pregunta: "¿Cómo se dice 'Familia' en italiano?", opciones: ["Famiglia", "Family", "Famille", "Familia"], respuesta: "Famiglia" },
  { categoria: "Italiano", pregunta: "¿Cómo se dice 'Casa' en italiano?", opciones: ["Casa", "House", "Maison", "Casa"], respuesta: "Casa" },
  { categoria: "Italiano", pregunta: "¿Cómo se dice 'Escuela' en italiano?", opciones: ["Scuola", "School", "École", "Escuela"], respuesta: "Scuola" },
  { categoria: "Italiano", pregunta: "¿Cómo se dice 'Perro' en italiano?", opciones: ["Cane", "Dog", "Chien", "Perro"], respuesta: "Cane" },
  { categoria: "Italiano", pregunta: "¿Cómo se dice 'Gato' en italiano?", opciones: ["Gatto", "Cat", "Chat", "Gato"], respuesta: "Gatto" },
  { categoria: "Italiano", pregunta: "¿Cómo se dice 'Agua' en italiano?", opciones: ["Acqua", "Water", "Eau", "Agua"], respuesta: "Acqua" },
  { categoria: "Italiano", pregunta: "¿Cómo se dice 'Comida' en italiano?", opciones: ["Cibo", "Food", "Nourriture", "Comida"], respuesta: "Cibo" },
  { categoria: "Italiano", pregunta: "¿Cómo se dice 'Feliz' en italiano?", opciones: ["Felice", "Happy", "Heureux", "Feliz"], respuesta: "Felice" },
  { categoria: "Italiano", pregunta: "¿Cómo se dice 'Triste' en italiano?", opciones: ["Triste", "Sad", "Triste", "Triste"], respuesta: "Triste" },
  { categoria: "Italiano", pregunta: "¿Cómo se dice 'Cansado' en italiano?", opciones: ["Stanco", "Tired", "Fatigué", "Cansado"], respuesta: "Stanco" },
  { categoria: "Italiano", pregunta: "¿Cómo se dice 'Dormir' en italiano?", opciones: ["Dormire", "Sleep", "Dormir", "Dormir"], respuesta: "Dormire" },
  { categoria: "Italiano", pregunta: "¿Cómo se dice 'Leer' en italiano?", opciones: ["Leggere", "Read", "Lire", "Leer"], respuesta: "Leggere" },
  { categoria: "Italiano", pregunta: "¿Cómo se dice 'Escribir' en italiano?", opciones: ["Scrivere", "Write", "Écrire", "Escribir"], respuesta: "Scrivere" },
  { categoria: "Italiano", pregunta: "¿Cómo se dice 'Escuchar' en italiano?", opciones: ["Ascoltare", "Listen", "Écouter", "Escuchar"], respuesta: "Ascoltare" },
  { categoria: "Italiano", pregunta: "¿Cómo se dice 'Hablar' en italiano?", opciones: ["Parlare", "Speak", "Parler", "Hablar"], respuesta: "Parlare" },
  { categoria: "Italiano", pregunta: "¿Cómo se dice 'Rápido' en italiano?", opciones: ["Veloce", "Fast", "Rapide", "Rápido"], respuesta: "Veloce" },
  { categoria: "Italiano", pregunta: "¿Cómo se dice 'Lento' en italiano?", opciones: ["Lento", "Slow", "Lent", "Lento"], respuesta: "Lento" },
  { categoria: "Italiano", pregunta: "¿Cómo se dice 'Grande' en italiano?", opciones: ["Grande", "Big", "Grand", "Grande"], respuesta: "Grande" },
  { categoria: "Italiano", pregunta: "¿Cómo se dice 'Pequeño' en italiano?", opciones: ["Piccolo", "Small", "Petit", "Pequeño"], respuesta: "Piccolo" },
  { categoria: "Italiano", pregunta: "¿Cómo se dice 'Nuevo' en italiano?", opciones: ["Nuovo", "New", "Nouveau", "Nuevo"], respuesta: "Nuovo" },
  { categoria: "Italiano", pregunta: "¿Cómo se dice 'Viejo' en italiano?", opciones: ["Vecchio", "Old", "Ancien", "Viejo"], respuesta: "Vecchio" },
  { categoria: "Italiano", pregunta: "¿Cómo se dice 'Frío' en italiano?", opciones: ["Freddo", "Cold", "Froid", "Frío"], respuesta: "Freddo" },
  { categoria: "Italiano", pregunta: "¿Cómo se dice 'Caliente' en italiano?", opciones: ["Caldo", "Hot", "Chaud", "Caliente"], respuesta: "Caldo" },
  { categoria: "Italiano", pregunta: "¿Cómo se dice 'Hoy' en italiano?", opciones: ["Oggi", "Today", "Aujourd'hui", "Hoy"], respuesta: "Oggi" },
  { categoria: "Italiano", pregunta: "¿Cómo se dice 'Ayer' en italiano?", opciones: ["Ieri", "Yesterday", "Hier", "Ayer"], respuesta: "Ieri" },
  { categoria: "Italiano", pregunta: "¿Cómo se dice 'Mañana' en italiano?", opciones: ["Domani", "Tomorrow", "Demain", "Mañana"], respuesta: "Domani" },
  { categoria: "Italiano", pregunta: "¿Cómo se dice 'Lunes' en italiano?", opciones: ["Lunedì", "Monday", "Lundi", "Lunes"], respuesta: "Lunedì" },
  { categoria: "Italiano", pregunta: "¿Cómo se dice 'Martes' en italiano?", opciones: ["Martedì", "Tuesday", "Mardi", "Martes"], respuesta: "Martedì" },
  { categoria: "Italiano", pregunta: "¿Cómo se dice 'Miércoles' en italiano?", opciones: ["Mercoledì", "Wednesday", "Mercredi", "Miércoles"], respuesta: "Mercoledì" },
  { categoria: "Italiano", pregunta: "¿Cómo se dice 'Jueves' en italiano?", opciones: ["Giovedì", "Thursday", "Jeudi", "Jueves"], respuesta: "Giovedì" },
  { categoria: "Italiano", pregunta: "¿Cómo se dice 'Viernes' en italiano?", opciones: ["Venerdì", "Friday", "Vendredi", "Viernes"], respuesta: "Venerdì" },
  { categoria: "Italiano", pregunta: "¿Cómo se dice 'Sábado' en italiano?", opciones: ["Sabato", "Saturday", "Samedi", "Sábado"], respuesta: "Sabato" },
  { categoria: "Italiano", pregunta: "¿Cómo se dice 'Domingo' en italiano?", opciones: ["Domenica", "Sunday", "Dimanche", "Domingo"], respuesta: "Domenica" },
  { categoria: "Italiano", pregunta: "¿Cómo se dice 'Rojo' en italiano?", opciones: ["Rosso", "Red", "Rouge", "Rojo"], respuesta: "Rosso" },
  { categoria: "Italiano", pregunta: "¿Cómo se dice 'Azul' en italiano?", opciones: ["Blu", "Blue", "Bleu", "Azul"], respuesta: "Blu" },
  { categoria: "Italiano", pregunta: "¿Cómo se dice 'Verde' en italiano?", opciones: ["Verde", "Green", "Vert", "Verde"], respuesta: "Verde" },
  { categoria: "Italiano", pregunta: "¿Cómo se dice 'Negro' en italiano?", opciones: ["Nero", "Black", "Noir", "Negro"], respuesta: "Nero" },
  { categoria: "Italiano", pregunta: "¿Cómo se dice 'Blanco' en italiano?", opciones: ["Bianco", "White", "Blanc", "Blanco"], respuesta: "Bianco" },
  { categoria: "Italiano", pregunta: "¿Cómo se dice 'Uno' en italiano?", opciones: ["Uno", "One", "Un", "Uno"], respuesta: "Uno" },
  { categoria: "Italiano", pregunta: "¿Cómo se dice 'Dos' en italiano?", opciones: ["Due", "Two", "Deux", "Dos"], respuesta: "Due" },
  { categoria: "Italiano", pregunta: "¿Cómo se dice 'Tres' en italiano?", opciones: ["Tre", "Three", "Trois", "Tres"], respuesta: "Tre" },
  { categoria: "Italiano", pregunta: "¿Cómo se dice 'Cuatro' en italiano?", opciones: ["Quattro", "Four", "Quatre", "Cuatro"], respuesta: "Quattro" },
  { categoria: "Italiano", pregunta: "¿Cómo se dice 'Cinco' en italiano?", opciones: ["Cinque", "Five", "Cinq", "Cinco"], respuesta: "Cinque" },
  { categoria: "Italiano", pregunta: "¿Cómo se dice 'Seis' en italiano?", opciones: ["Sei", "Six", "Six", "Seis"], respuesta: "Sei" },
  { categoria: "Italiano", pregunta: "¿Cómo se dice 'Siete' en italiano?", opciones: ["Sette", "Seven", "Sept", "Siete"], respuesta: "Sette" },
  { categoria: "Italiano", pregunta: "¿Cómo se dice 'Ocho' en italiano?", opciones: ["Otto", "Eight", "Huit", "Ocho"], respuesta: "Otto" },
  { categoria: "Italiano", pregunta: "¿Cómo se dice 'Nueve' en italiano?", opciones: ["Nove", "Nine", "Neuf", "Nueve"], respuesta: "Nove" },
  { categoria: "Italiano", pregunta: "¿Cómo se dice 'Diez' en italiano?", opciones: ["Dieci", "Ten", "Dix", "Diez"], respuesta: "Dieci" },
];
