const preguntasMusica = [
  { categoria: "Música", pregunta: "¿Quién es conocido como el 'Rey del Pop'?", opciones: ["Michael Jackson", "Elvis Presley", "Prince", "Freddie Mercury"], respuesta: "Michael Jackson" },
  { categoria: "Música", pregunta: "¿Qué banda británica lanzó el álbum 'Abbey Road'?", opciones: ["The Beatles", "Queen", "Pink Floyd", "The Rolling Stones"], respuesta: "The Beatles" },
  { categoria: "Música", pregunta: "¿Quién es la cantante de 'Rolling in the Deep'?", opciones: ["Adele", "Beyoncé", "Lady Gaga", "Taylor Swift"], respuesta: "Adele" },
  { categoria: "Música", pregunta: "¿Qué instrumento toca tradicionalmente un violinista?", opciones: ["Violín", "Guitarra", "Piano", "Saxofón"], respuesta: "Violín" },
  { categoria: "Música", pregunta: "¿Qué género musical es originario de Jamaica?", opciones: ["Reggae", "Salsa", "Rock", "Jazz"], respuesta: "Reggae" },
  { categoria: "Música", pregunta: "¿Quién compuso la Novena Sinfonía (Oda a la Alegría)?", opciones: ["Ludwig van Beethoven", "Mozart", "Bach", "Chopin"], respuesta: "Ludwig van Beethoven" },
  { categoria: "Música", pregunta: "¿Qué cantante es conocido como 'La Reina del Pop'?", opciones: ["Madonna", "Britney Spears", "Celine Dion", "Shakira"], respuesta: "Madonna" },
  { categoria: "Música", pregunta: "¿Qué banda lanzó la canción 'Bohemian Rhapsody'?", opciones: ["Queen", "The Beatles", "ABBA", "Pink Floyd"], respuesta: "Queen" },
  { categoria: "Música", pregunta: "¿Qué instrumento tiene teclas blancas y negras?", opciones: ["Piano", "Guitarra", "Batería", "Violín"], respuesta: "Piano" },
  { categoria: "Música", pregunta: "¿Qué cantante lanzó el álbum '1989'?", opciones: ["Taylor Swift", "Katy Perry", "Ariana Grande", "Selena Gomez"], respuesta: "Taylor Swift" },
  { categoria: "Música", pregunta: "¿Qué género musical es originario de Nueva Orleans, EE.UU.?", opciones: ["Jazz", "Rock", "Reggae", "Pop"], respuesta: "Jazz" },
  { categoria: "Música", pregunta: "¿Qué grupo es famoso por la canción 'Hotel California'?", opciones: ["The Eagles", "The Beatles", "Queen", "Led Zeppelin"], respuesta: "The Eagles" },
  { categoria: "Música", pregunta: "¿Quién es el vocalista principal de U2?", opciones: ["Bono", "Sting", "Freddie Mercury", "Mick Jagger"], respuesta: "Bono" },
  { categoria: "Música", pregunta: "¿Qué banda británica lanzó el álbum 'Dark Side of the Moon'?", opciones: ["Pink Floyd", "Queen", "The Beatles", "Led Zeppelin"], respuesta: "Pink Floyd" },
  { categoria: "Música", pregunta: "¿Quién es conocido como 'El Rey del Rock'?", opciones: ["Elvis Presley", "Michael Jackson", "Prince", "David Bowie"], respuesta: "Elvis Presley" },
  { categoria: "Música", pregunta: "¿Qué género musical es originario de Cuba?", opciones: ["Salsa", "Reggae", "Blues", "Country"], respuesta: "Salsa" },
  { categoria: "Música", pregunta: "¿Quién cantó 'Like a Virgin'?", opciones: ["Madonna", "Lady Gaga", "Britney Spears", "Celine Dion"], respuesta: "Madonna" },
  { categoria: "Música", pregunta: "¿Qué instrumento tiene cuerdas y se toca con arco?", opciones: ["Violín", "Guitarra", "Piano", "Flauta"], respuesta: "Violín" },
  { categoria: "Música", pregunta: "¿Quién es la cantante de 'Hello'?", opciones: ["Adele", "Beyoncé", "Lady Gaga", "Taylor Swift"], respuesta: "Adele" },
  { categoria: "Música", pregunta: "¿Qué banda lanzó la canción 'Stairway to Heaven'?", opciones: ["Led Zeppelin", "The Rolling Stones", "The Beatles", "Queen"], respuesta: "Led Zeppelin" },
  { categoria: "Música", pregunta: "¿Qué instrumento se usa en la música hawaiana y tiene cuerdas?", opciones: ["Ukelele", "Guitarra", "Piano", "Violín"], respuesta: "Ukelele" },
  { categoria: "Música", pregunta: "¿Quién es conocido como 'El Rey del Soul'?", opciones: ["James Brown", "Michael Jackson", "Prince", "Elvis Presley"], respuesta: "James Brown" },
  { categoria: "Música", pregunta: "¿Qué banda lanzó 'Sweet Child O' Mine'?", opciones: ["Guns N' Roses", "Nirvana", "Metallica", "AC/DC"], respuesta: "Guns N' Roses" },
  { categoria: "Música", pregunta: "¿Qué cantante lanzó 'Shape of You'?", opciones: ["Ed Sheeran", "Justin Bieber", "Shawn Mendes", "Sam Smith"], respuesta: "Ed Sheeran" },
  { categoria: "Música", pregunta: "¿Qué género musical es originario de Argentina?", opciones: ["Tango", "Salsa", "Reggae", "Jazz"], respuesta: "Tango" },
  { categoria: "Música", pregunta: "¿Qué cantante lanzó el álbum 'Lemonade'?", opciones: ["Beyoncé", "Rihanna", "Adele", "Lady Gaga"], respuesta: "Beyoncé" },
  { categoria: "Música", pregunta: "¿Qué instrumento tiene teclas y cuerdas y se toca con martillos?", opciones: ["Piano", "Guitarra", "Arpa", "Órgano"], respuesta: "Piano" },
  { categoria: "Música", pregunta: "¿Qué banda lanzó la canción 'Smells Like Teen Spirit'?", opciones: ["Nirvana", "Pearl Jam", "Soundgarden", "Alice in Chains"], respuesta: "Nirvana" },
  { categoria: "Música", pregunta: "¿Quién compuso 'La primavera' de Las Cuatro Estaciones?", opciones: ["Antonio Vivaldi", "Mozart", "Beethoven", "Bach"], respuesta: "Antonio Vivaldi" },
  { categoria: "Música", pregunta: "¿Qué cantante lanzó 'Bad Romance'?", opciones: ["Lady Gaga", "Madonna", "Katy Perry", "Adele"], respuesta: "Lady Gaga" },
  { categoria: "Música", pregunta: "¿Qué género musical se originó en el sur de Estados Unidos y mezcla blues y gospel?", opciones: ["Soul", "Jazz", "Rock", "Pop"], respuesta: "Soul" },
  { categoria: "Música", pregunta: "¿Quién es el líder de la banda Coldplay?", opciones: ["Chris Martin", "Bono", "Freddie Mercury", "Thom Yorke"], respuesta: "Chris Martin" },
  { categoria: "Música", pregunta: "¿Qué banda lanzó 'Imagine'?", opciones: ["The Beatles", "John Lennon", "Queen", "Pink Floyd"], respuesta: "John Lennon" },
  { categoria: "Música", pregunta: "¿Qué instrumento se toca soplando aire?", opciones: ["Flauta", "Guitarra", "Piano", "Batería"], respuesta: "Flauta" },
  { categoria: "Música", pregunta: "¿Qué banda lanzó 'Back in Black'?", opciones: ["AC/DC", "Led Zeppelin", "Queen", "Nirvana"], respuesta: "AC/DC" },
  { categoria: "Música", pregunta: "¿Quién es el vocalista principal de Maroon 5?", opciones: ["Adam Levine", "Chris Martin", "Bruno Mars", "Justin Timberlake"], respuesta: "Adam Levine" },
  { categoria: "Música", pregunta: "¿Qué banda lanzó 'Livin' on a Prayer'?", opciones: ["Bon Jovi", "Aerosmith", "Guns N' Roses", "Def Leppard"], respuesta: "Bon Jovi" },
  { categoria: "Música", pregunta: "¿Qué cantante lanzó 'Thriller'?", opciones: ["Michael Jackson", "Prince", "Elvis Presley", "Freddie Mercury"], respuesta: "Michael Jackson" },
  { categoria: "Música", pregunta: "¿Qué banda lanzó 'Paint It Black'?", opciones: ["The Rolling Stones", "The Beatles", "Led Zeppelin", "Queen"], respuesta: "The Rolling Stones" },
  { categoria: "Música", pregunta: "¿Quién es el vocalista de Aerosmith?", opciones: ["Steven Tyler", "Axl Rose", "Bono", "Dave Grohl"], respuesta: "Steven Tyler" },
  { categoria: "Música", pregunta: "¿Qué banda lanzó 'Wonderwall'?", opciones: ["Oasis", "Blur", "Coldplay", "Radiohead"], respuesta: "Oasis" },
  { categoria: "Música", pregunta: "¿Quién es conocido como 'El Rey del Reggaetón'?", opciones: ["Daddy Yankee", "Bad Bunny", "J Balvin", "Ozuna"], respuesta: "Daddy Yankee" },
  { categoria: "Música", pregunta: "¿Qué cantante lanzó 'Firework'?", opciones: ["Katy Perry", "Lady Gaga", "Rihanna", "Adele"], respuesta: "Katy Perry" },
  { categoria: "Música", pregunta: "¿Qué banda lanzó 'Sweet Home Alabama'?", opciones: ["Lynyrd Skynyrd", "The Eagles", "Queen", "AC/DC"], respuesta: "Lynyrd Skynyrd" },
  { categoria: "Música", pregunta: "¿Quién es la cantante de 'Umbrella'?", opciones: ["Rihanna", "Beyoncé", "Adele", "Katy Perry"], respuesta: "Rihanna" },
  { categoria: "Música", pregunta: "¿Qué instrumento tiene seis cuerdas y se toca con los dedos o púa?", opciones: ["Guitarra", "Violín", "Piano", "Bajo"], respuesta: "Guitarra" },
  { categoria: "Música", pregunta: "¿Quién compuso la ópera 'La Traviata'?", opciones: ["Giuseppe Verdi", "Mozart", "Beethoven", "Puccini"], respuesta: "Giuseppe Verdi" },
  { categoria: "Música", pregunta: "¿Qué banda lanzó 'Enter Sandman'?", opciones: ["Metallica", "Iron Maiden", "AC/DC", "Nirvana"], respuesta: "Metallica" },
  { categoria: "Música", pregunta: "¿Quién es la cantante de 'Poker Face'?", opciones: ["Lady Gaga", "Katy Perry", "Madonna", "Rihanna"], respuesta: "Lady Gaga" },
  { categoria: "Música", pregunta: "¿Qué banda lanzó 'Nothing Else Matters'?", opciones: ["Metallica", "Nirvana", "AC/DC", "Iron Maiden"], respuesta: "Metallica" },
  { categoria: "Música", pregunta: "¿Qué género musical es típico de Brasil?", opciones: ["Samba", "Reggae", "Jazz", "Pop"], respuesta: "Samba" },
  { categoria: "Música", pregunta: "¿Quién es conocido como 'El Rey del Hip Hop'?", opciones: ["Tupac Shakur", "Jay-Z", "Eminem", "Dr. Dre"], respuesta: "Tupac Shakur" }
];
