const preguntasTecnologia = [
  { p: "¿Qué significa HTML?", o: ["HyperText Markup Language", "HyperText Machine Language", "HighText Markup Language", "HyperTool Markup Language"], r: "HyperText Markup Language" },
  { p: "¿Qué significa CSS?", o: ["Cascading Style Sheets", "Computer Style Sheets", "Creative Style System", "Control Style Sheets"], r: "Cascading Style Sheets" },
  { p: "¿Qué lenguaje se utiliza principalmente para la programación web del lado del cliente?", o: ["JavaScript", "Python", "C++", "PHP"], r: "JavaScript" },
  { p: "¿Qué es una variable en programación?", o: ["Un espacio para almacenar datos", "Una función matemática", "Un tipo de archivo", "Un error de código"], r: "Un espacio para almacenar datos" },
  { p: "¿Qué significa API?", o: ["Application Programming Interface", "Advanced Programming Integration", "Application Process Interface", "Applied Programming Instance"], r: "Application Programming Interface" },
  { p: "¿Qué lenguaje se usa principalmente en desarrollo de aplicaciones iOS?", o: ["Swift", "Java", "Python", "C#"], r: "Swift" },
  { p: "¿Qué significa SQL?", o: ["Structured Query Language", "Simple Query Language", "Structured Question Logic", "Sequential Query Language"], r: "Structured Query Language" },
  { p: "¿Qué es Git?", o: ["Sistema de control de versiones", "Lenguaje de programación", "Base de datos", "Framework web"], r: "Sistema de control de versiones" },
  { p: "¿Qué es GitHub?", o: ["Plataforma de alojamiento de código", "Lenguaje de programación", "Editor de texto", "Sistema operativo"], r: "Plataforma de alojamiento de código" },
  { p: "¿Qué significa IDE?", o: ["Integrated Development Environment", "Intelligent Development Editor", "Interactive Design Engine", "Internal Development Environment"], r: "Integrated Development Environment" },
  { p: "¿Qué significa 'frontend'?", o: ["Parte visible de una aplicación web", "Base de datos de la aplicación", "Servidor de la aplicación", "Código backend"], r: "Parte visible de una aplicación web" },
  { p: "¿Qué significa 'backend'?", o: ["Parte del servidor y lógica de la aplicación", "Diseño gráfico de la app", "Estilo de la página web", "Editor de código"], r: "Parte del servidor y lógica de la aplicación" },
  { p: "¿Qué es una función en programación?", o: ["Bloque de código que realiza una tarea", "Variable especial", "Error de ejecución", "Archivo de programa"], r: "Bloque de código que realiza una tarea" },
  { p: "¿Qué es un bucle o loop?", o: ["Repetición de un bloque de código", "Variable temporal", "Error de código", "Interfaz de usuario"], r: "Repetición de un bloque de código" },
  { p: "¿Qué es Python?", o: ["Lenguaje de programación", "Sistema operativo", "Base de datos", "Editor de código"], r: "Lenguaje de programación" },
  { p: "¿Qué es Java?", o: ["Lenguaje de programación", "Sistema operativo", "Framework web", "Aplicación de escritorio"], r: "Lenguaje de programación" },
  { p: "¿Qué es C++?", o: ["Lenguaje de programación", "Base de datos", "Editor de texto", "Sistema operativo"], r: "Lenguaje de programación" },
  { p: "¿Qué es un framework?", o: ["Conjunto de herramientas y librerías para programar", "Lenguaje de programación", "Editor de código", "Servidor web"], r: "Conjunto de herramientas y librerías para programar" },
  { p: "¿Qué es un IDE?", o: ["Entorno de desarrollo integrado", "Lenguaje de programación", "Servidor web", "Base de datos"], r: "Entorno de desarrollo integrado" },
  { p: "¿Qué significa IoT?", o: ["Internet of Things", "Interface of Technology", "Internet of Tools", "Integration of Technology"], r: "Internet of Things" },
  { p: "¿Qué es un servidor web?", o: ["Computadora que sirve páginas web", "Lenguaje de programación", "Base de datos", "Editor de texto"], r: "Computadora que sirve páginas web" },
  { p: "¿Qué es un cliente en informática?", o: ["Programa o dispositivo que solicita servicios de un servidor", "Base de datos", "Editor de código", "Lenguaje de programación"], r: "Programa o dispositivo que solicita servicios de un servidor" },
  { p: "¿Qué es CSS Grid?", o: ["Sistema de diseño de páginas web", "Lenguaje de programación", "Base de datos", "Editor de texto"], r: "Sistema de diseño de páginas web" },
  { p: "¿Qué es un algoritmo?", o: ["Conjunto de instrucciones para resolver un problema", "Variable temporal", "Error de código", "Lenguaje de programación"], r: "Conjunto de instrucciones para resolver un problema" },
  { p: "¿Qué es la nube o cloud computing?", o: ["Almacenamiento y servicios en internet", "Lenguaje de programación", "Editor de código", "Base de datos local"], r: "Almacenamiento y servicios en internet" },
  { p: "¿Qué es un bug?", o: ["Error en el código", "Variable especial", "Función", "Framework"], r: "Error en el código" },
  { p: "¿Qué es un commit en Git?", o: ["Guardar cambios en el repositorio", "Eliminar archivos", "Descargar código", "Crear rama"], r: "Guardar cambios en el repositorio" },
  { p: "¿Qué es un pull request?", o: ["Propuesta de cambios para integrarse al repositorio", "Descargar archivos", "Editar código local", "Crear un nuevo repositorio"], r: "Propuesta de cambios para integrarse al repositorio" },
  { p: "¿Qué es una rama o branch en Git?", o: ["Línea de desarrollo independiente", "Archivo de configuración", "Variable especial", "Error de código"], r: "Línea de desarrollo independiente" },
  { p: "¿Qué es npm?", o: ["Administrador de paquetes para JavaScript", "Lenguaje de programación", "Framework web", "Editor de texto"], r: "Administrador de paquetes para JavaScript" },
  { p: "¿Qué es JSON?", o: ["Formato de intercambio de datos", "Lenguaje de programación", "Editor de código", "Base de datos"], r: "Formato de intercambio de datos" },
  { p: "¿Qué es REST?", o: ["Estilo de arquitectura para APIs", "Lenguaje de programación", "Editor de texto", "Framework web"], r: "Estilo de arquitectura para APIs" },
  { p: "¿Qué es HTTPS?", o: ["Protocolo seguro para la web", "Lenguaje de programación", "Base de datos", "Editor de código"], r: "Protocolo seguro para la web" },
  { p: "¿Qué es HTTP?", o: ["Protocolo de transferencia de hipertexto", "Lenguaje de programación", "Base de datos", "Editor de código"], r: "Protocolo de transferencia de hipertexto" },
  { p: "¿Qué es un framework frontend popular?", o: ["React", "Python", "Java", "SQL"], r: "React" },
  { p: "¿Qué es un framework backend popular?", o: ["Node.js", "CSS", "HTML", "Swift"], r: "Node.js" },
  { p: "¿Qué es TypeScript?", o: ["Lenguaje basado en JavaScript con tipado", "Editor de código", "Base de datos", "Framework web"], r: "Lenguaje basado en JavaScript con tipado" },
  { p: "¿Qué es una API RESTful?", o: ["API que sigue principios REST", "Base de datos", "Editor de texto", "Framework web"], r: "API que sigue principios REST" },
  { p: "¿Qué es un servidor?", o: ["Computadora que proporciona servicios a otras", "Lenguaje de programación", "Variable", "Función"], r: "Computadora que proporciona servicios a otras" },
  { p: "¿Qué es un cliente?", o: ["Dispositivo que solicita servicios de un servidor", "Lenguaje de programación", "Variable", "Función"], r: "Dispositivo que solicita servicios de un servidor" },
  { p: "¿Qué es un endpoint en una API?", o: ["URL que accede a recursos", "Variable temporal", "Framework", "Base de datos"], r: "URL que accede a recursos" },
  { p: "¿Qué significa OOP?", o: ["Programación Orientada a Objetos", "Lenguaje de programación", "Base de datos", "Editor de código"], r: "Programación Orientada a Objetos" },
  { p: "¿Qué es una clase en OOP?", o: ["Plantilla para crear objetos", "Variable especial", "Error de código", "Función"], r: "Plantilla para crear objetos" },
  { p: "¿Qué es un objeto en OOP?", o: ["Instancia de una clase", "Variable temporal", "Error de código", "Framework"], r: "Instancia de una clase" },
  { p: "¿Qué es encapsulación?", o: ["Ocultar detalles internos de un objeto", "Variable especial", "Función", "Framework"], r: "Ocultar detalles internos de un objeto" },
  { p: "¿Qué es herencia en OOP?", o: ["Clase que comparte propiedades de otra", "Variable especial", "Función", "Framework"], r: "Clase que comparte propiedades de otra" },
  { p: "¿Qué es polimorfismo?", o: ["Objetos que se comportan de diferentes formas", "Variable especial", "Función", "Framework"], r: "Objetos que se comportan de diferentes formas" },
  { p: "¿Qué es un array o lista?", o: ["Colección de datos", "Variable especial", "Función", "Objeto"], r: "Colección de datos" },
  { p: "¿Qué es un diccionario o map?", o: ["Colección de pares clave-valor", "Variable especial", "Función", "Array"], r: "Colección de pares clave-valor" },
  { p: "¿Qué es un loop for?", o: ["Bucle que itera un número fijo de veces", "Variable temporal", "Función", "Objeto"], r: "Bucle que itera un número fijo de veces" },
  { p: "¿Qué es un loop while?", o: ["Bucle que se repite mientras una condición sea verdadera", "Variable temporal", "Función", "Objeto"], r: "Bucle que se repite mientras una condición sea verdadera" },
  { p: "¿Qué es un condicional if?", o: ["Ejecuta código si la condición es verdadera", "Variable temporal", "Función", "Loop"], r: "Ejecuta código si la condición es verdadera" },
  { p: "¿Qué es un condicional else?", o: ["Código que se ejecuta si la condición del if es falsa", "Variable temporal", "Función", "Loop"], r: "Código que se ejecuta si la condición del if es falsa" },
  { p: "¿Qué es un condicional else if?", o: ["Verifica otra condición si la primera es falsa", "Variable temporal", "Función", "Loop"], r: "Verifica otra condición si la primera es falsa" },
  { p: "¿Qué es una base de datos SQL?", o: ["Base de datos relacional", "Base de datos no relacional", "Lenguaje de programación", "Framework"], r: "Base de datos relacional" },
  { p: "¿Qué es una base de datos NoSQL?", o: ["Base de datos no relacional", "Base de datos relacional", "Lenguaje de programación", "Framework"], r: "Base de datos no relacional" },
  { p: "¿Qué es un query?", o: ["Consulta a la base de datos", "Variable temporal", "Función", "Loop"], r: "Consulta a la base de datos" },
  { p: "¿Qué es un join en SQL?", o: ["Combinar tablas según una relación", "Variable temporal", "Función", "Loop"], r: "Combinar tablas según una relación" },
  { p: "¿Qué es un index en base de datos?", o: ["Optimiza la búsqueda de registros", "Variable temporal", "Función", "Loop"], r: "Optimiza la búsqueda de registros" },
  { p: "¿Qué es un trigger en SQL?", o: ["Acción automática ante un evento en la base de datos", "Variable temporal", "Función", "Loop"], r: "Acción automática ante un evento en la base de datos" },
  { p: "¿Qué es un commit?", o: ["Guardar cambios en Git", "Variable temporal", "Función", "Loop"], r: "Guardar cambios en Git" },
  { p: "¿Qué es un merge?", o: ["Combinar ramas en Git", "Variable temporal", "Función", "Loop"], r: "Combinar ramas en Git" },
  { p: "¿Qué es un branch?", o: ["Rama de desarrollo en Git", "Variable temporal", "Función", "Loop"], r: "Rama de desarrollo en Git" },
  { p: "¿Qué es un push?", o: ["Enviar cambios al repositorio remoto", "Variable temporal", "Función", "Loop"], r: "Enviar cambios al repositorio remoto" },
  { p: "¿Qué es un pull?", o: ["Traer cambios del repositorio remoto", "Variable temporal", "Función", "Loop"], r: "Traer cambios del repositorio remoto" },
  { p: "¿Qué es debugging?", o: ["Encontrar y corregir errores en el código", "Variable temporal", "Función", "Loop"], r: "Encontrar y corregir errores en el código" },
  { p: "¿Qué es un breakpoint?", o: ["Punto donde el código se detiene para depuración", "Variable temporal", "Función", "Loop"], r: "Punto donde el código se detiene para depuración" },
  { p: "¿Qué es un stack?", o: ["Estructura de datos LIFO", "Variable temporal", "Función", "Loop"], r: "Estructura de datos LIFO" },
  { p: "¿Qué es una queue?", o: ["Estructura de datos FIFO", "Variable temporal", "Función", "Loop"], r: "Estructura de datos FIFO" },
  { p: "¿Qué es Big Data?", o: ["Conjunto de datos muy grande y complejo", "Variable temporal", "Función", "Loop"], r: "Conjunto de datos muy grande y complejo" },
  { p: "¿Qué es Machine Learning?", o: ["Aprendizaje automático por algoritmos", "Variable temporal", "Función", "Loop"], r: "Aprendizaje automático por algoritmos" },
  { p: "¿Qué es Inteligencia Artificial?", o: ["Simulación de inteligencia humana en máquinas", "Variable temporal", "Función", "Loop"], r: "Simulación de inteligencia humana en máquinas" },
  { p: "¿Qué es un servidor cloud?", o: ["Servidor alojado en la nube", "Variable temporal", "Función", "Loop"], r: "Servidor alojado en la nube" },
  { p: "¿Qué es Docker?", o: ["Plataforma de contenedores", "Lenguaje de programación", "Base de datos", "Editor de código"], r: "Plataforma de contenedores" },
  { p: "¿Qué es Kubernetes?", o: ["Orquestador de contenedores", "Lenguaje de programación", "Base de datos", "Editor de código"], r: "Orquestador de contenedores" },
  { p: "¿Qué es una VPN?", o: ["Red privada virtual", "Lenguaje de programación", "Base de datos", "Editor de código"], r: "Red privada virtual" },
  { p: "¿Qué es phishing?", o: ["Intento de robar información engañando al usuario", "Lenguaje de programación", "Base de datos", "Editor de código"], r: "Intento de robar información engañando al usuario" },
  { p: "¿Qué es malware?", o: ["Software malicioso", "Lenguaje de programación", "Base de datos", "Editor de código"], r: "Software malicioso" },
  { p: "¿Qué es ransomware?", o: ["Malware que bloquea archivos hasta pagar rescate", "Lenguaje de programación", "Base de datos", "Editor de código"], r: "Malware que bloquea archivos hasta pagar rescate" },
  { p: "¿Qué es un firewall?", o: ["Sistema de seguridad que controla tráfico de red", "Lenguaje de programación", "Base de datos", "Editor de código"], r: "Sistema de seguridad que controla tráfico de red" },
  { p: "¿Qué es un proxy?", o: ["Servidor intermedio que reenvía solicitudes", "Lenguaje de programación", "Base de datos", "Editor de código"], r: "Servidor intermedio que reenvía solicitudes" },
  { p: "¿Qué es HTTP status 404?", o: ["Página no encontrada", "Éxito", "Redirección", "Error de servidor"], r: "Página no encontrada" },
  { p: "¿Qué es HTTP status 200?", o: ["Éxito", "Página no encontrada", "Redirección", "Error de servidor"], r: "Éxito" },
  { p: "¿Qué es HTTPS?", o: ["HTTP seguro", "HTTP inseguro", "FTP", "SSH"], r: "HTTP seguro" },
  { p: "¿Qué es SSH?", o: ["Protocolo de acceso seguro a servidores", "Lenguaje de programación", "Base de datos", "Editor de código"], r: "Protocolo de acceso seguro a servidores" },
  { p: "¿Qué es FTP?", o: ["Protocolo de transferencia de archivos", "Lenguaje de programación", "Base de datos", "Editor de código"], r: "Protocolo de transferencia de archivos" },
  { p: "¿Qué es SaaS?", o: ["Software como servicio", "Lenguaje de programación", "Base de datos", "Editor de código"], r: "Software como servicio" },
  { p: "¿Qué es PaaS?", o: ["Plataforma como servicio", "Lenguaje de programación", "Base de datos", "Editor de código"], r: "Plataforma como servicio" },
  { p: "¿Qué es IaaS?", o: ["Infraestructura como servicio", "Lenguaje de programación", "Base de datos", "Editor de código"], r: "Infraestructura como servicio" },
  { p: "¿Qué es un IDE popular para JavaScript?", o: ["VS Code", "Photoshop", "Excel", "Notepad"], r: "VS Code" },
  { p: "¿Qué es un editor de texto simple?", o: ["Notepad", "VS Code", "Eclipse", "IntelliJ"], r: "Notepad" },
  { p: "¿Qué es un sistema operativo?", o: ["Software que gestiona hardware y recursos", "Lenguaje de programación", "Base de datos", "Editor de código"], r: "Software que gestiona hardware y recursos" },
  { p: "¿Qué es Linux?", o: ["Sistema operativo", "Lenguaje de programación", "Framework web", "Editor de código"], r: "Sistema operativo" },
  { p: "¿Qué es Windows?", o: ["Sistema operativo", "Lenguaje de programación", "Framework web", "Editor de código"], r: "Sistema operativo" },
  { p: "¿Qué es macOS?", o: ["Sistema operativo", "Lenguaje de programación", "Framework web", "Editor de código"], r: "Sistema operativo" },
  { p: "¿Qué es un kernel?", o: ["Núcleo del sistema operativo", "Lenguaje de programación", "Editor de código", "Base de datos"], r: "Núcleo del sistema operativo" },
  { p: "¿Qué es un bit?", o: ["Unidad mínima de información", "Variable", "Función", "Archivo"], r: "Unidad mínima de información" },
  { p: "¿Qué es un byte?", o: ["8 bits", "1 bit", "16 bits", "Variable"], r: "8 bits" },
  { p: "¿Qué es Cloud Computing?", o: ["Computación en la nube", "Lenguaje de programación", "Editor de código", "Base de datos"], r: "Computación en la nube" },
  { p: "¿Qué es un microservicio?", o: ["Componente pequeño de software independiente", "Variable temporal", "Función", "Loop"], r: "Componente pequeño de software independiente" },
  { p: "¿Qué es un contenedor?", o: ["Entorno aislado para ejecutar aplicaciones", "Variable temporal", "Función", "Loop"], r: "Entorno aislado para ejecutar aplicaciones" },
  { p: "¿Qué es blockchain?", o: ["Cadena de bloques que registra transacciones", "Lenguaje de programación", "Editor de código", "Base de datos"], r: "Cadena de bloques que registra transacciones" },
  { p: "¿Qué es un smart contract?", o: ["Contrato ejecutable automáticamente en blockchain", "Lenguaje de programación", "Editor de código", "Base de datos"], r: "Contrato ejecutable automáticamente en blockchain" },
  { p: "¿Qué es IA?", o: ["Inteligencia Artificial", "Lenguaje de programación", "Editor de código", "Base de datos"], r: "Inteligencia Artificial" },
  { p: "¿Qué es un modelo de Machine Learning?", o: ["Algoritmo entrenado para predecir o clasificar", "Variable temporal", "Función", "Loop"], r: "Algoritmo entrenado para predecir o clasificar" }
];
