const preguntasUS = [
  {p:"¿Cuál es el deporte más popular en Estados Unidos?", o:["Fútbol americano","Béisbol","Baloncesto","Hockey sobre hielo"], r:"Fútbol americano"},
  {p:"¿Qué equipo de la NBA tiene más campeonatos?", o:["Boston Celtics","Los Angeles Lakers","Chicago Bulls","Golden State Warriors"], r:"Boston Celtics"},
  {p:"¿Qué lucha de UFC es conocida como la más importante?", o:["Ultimate Fighting Championship","Bellator","ONE Championship","Pride"], r:"Ultimate Fighting Championship"},
  {p:"¿Qué famoso boxeador es conocido como 'The Greatest'?", o:["Muhammad Ali","Mike Tyson","Floyd Mayweather","Joe Frazier"], r:"Muhammad Ali"},
  {p:"¿Qué famoso boxeador es conocido como 'Iron Mike'?", o:["Mike Tyson","Muhammad Ali","Evander Holyfield","George Foreman"], r:"Mike Tyson"},
  {p:"¿Qué deporte se juega en el Super Bowl?", o:["Fútbol americano","Baloncesto","Béisbol","Hockey"], r:"Fútbol americano"},
  {p:"¿Qué evento deportivo se celebra cada febrero y atrae a millones de espectadores?", o:["Super Bowl","NBA Finals","World Series","Olympics"], r:"Super Bowl"},
  {p:"¿Qué equipo de baloncesto tiene a Michael Jordan como ícono?", o:["Chicago Bulls","Los Angeles Lakers","Boston Celtics","Miami Heat"], r:"Chicago Bulls"},
  {p:"¿Qué equipo de la NFL es conocido como los 'Dallas Cowboys'?", o:["Dallas Cowboys","New England Patriots","Green Bay Packers","San Francisco 49ers"], r:"Dallas Cowboys"},
  {p:"¿Qué equipo de NFL es conocido como Patriots?", o:["New England Patriots","Dallas Cowboys","Green Bay Packers","San Francisco 49ers"], r:"New England Patriots"},
  {p:"¿Qué equipo de béisbol tiene la mayor rivalidad con los Yankees?", o:["Boston Red Sox","New York Mets","Chicago Cubs","Los Angeles Dodgers"], r:"Boston Red Sox"},
  {p:"¿Qué equipo de la MLB es conocido como 'Yankees'?", o:["New York Yankees","Boston Red Sox","Chicago Cubs","Los Angeles Dodgers"], r:"New York Yankees"},
  {p:"¿Qué famoso luchador WWE es conocido como 'The Rock'?", o:["Dwayne Johnson","John Cena","Stone Cold Steve Austin","Hulk Hogan"], r:"Dwayne Johnson"},
  {p:"¿Qué famoso luchador WWE es conocido como 'Stone Cold Steve Austin'?", o:["Stone Cold Steve Austin","The Rock","John Cena","Hulk Hogan"], r:"Stone Cold Steve Austin"},
  {p:"¿Qué famosa luchadora WWE es conocida como 'The Queen'?", o:["Charlotte Flair","Becky Lynch","Sasha Banks","Trish Stratus"], r:"Charlotte Flair"},
  {p:"¿Cuál es el animal nacional de EE.UU.?", o:["Águila calva","Bisonte","Oso grizzly","Lobo"], r:"Águila calva"},
  {p:"¿Qué famoso científico inventó la bombilla?", o:["Thomas Edison","Nikola Tesla","Alexander Graham Bell","Benjamin Franklin"], r:"Thomas Edison"},
  {p:"¿Qué científico formuló la teoría de la relatividad?", o:["Albert Einstein","Isaac Newton","Benjamin Franklin","Thomas Edison"], r:"Albert Einstein"},
  {p:"¿Qué famoso científico inventó el teléfono?", o:["Alexander Graham Bell","Thomas Edison","Nikola Tesla","Samuel Morse"], r:"Alexander Graham Bell"},
  {p:"¿Qué famoso científico inventó la radio?", o:["Nikola Tesla","Alexander Graham Bell","Thomas Edison","Albert Einstein"], r:"Nikola Tesla"},
  {p:"¿Qué científico inventó el fonógrafo?", o:["Thomas Edison","Nikola Tesla","Alexander Graham Bell","Benjamin Franklin"], r:"Thomas Edison"},
  {p:"¿Qué deporte es representado por la NFL?", o:["Fútbol americano","Baloncesto","Béisbol","Hockey"], r:"Fútbol americano"},
  {p:"¿Qué deporte es representado por la MLB?", o:["Béisbol","Fútbol americano","Baloncesto","Hockey"], r:"Béisbol"},
  {p:"¿Qué equipo de la NBA ganó más campeonatos?", o:["Boston Celtics","Los Angeles Lakers","Chicago Bulls","San Antonio Spurs"], r:"Boston Celtics"},
  {p:"¿Qué deporte es conocido como 'basketball'?", o:["Baloncesto","Fútbol","Fútbol americano","Béisbol"], r:"Baloncesto"},
  {p:"¿Qué famoso músico estadounidense es líder de The Beatles?", o:["Paul McCartney","Elvis Presley","Michael Jackson","Bruce Springsteen"], r:"Paul McCartney"},
  {p:"¿Cuál es el evento más famoso de lucha libre profesional en EE.UU.?", o:["WWE WrestleMania","UFC Fight Night","Bellator Live","NWA Show"], r:"WWE WrestleMania"},
  {p:"¿Qué famoso boxeador se enfrentó a Mike Tyson en 1990?", o:["Buster Douglas","Muhammad Ali","Evander Holyfield","George Foreman"], r:"Buster Douglas"},
  {p:"¿Qué famoso invento es de Nikola Tesla?", o:["Corriente alterna","Bombilla","Teléfono","Telégrafo"], r:"Corriente alterna"},
  {p:"¿Qué deporte es popular en universidades de EE.UU.?", o:["Fútbol americano","Baloncesto","Béisbol","Hockey"], r:"Fútbol americano"},
  {p:"¿Qué equipo de baloncesto juega en Los Ángeles y tiene múltiples campeonatos?", o:["Los Angeles Lakers","Los Angeles Clippers","Golden State Warriors","Chicago Bulls"], r:"Los Angeles Lakers"},
  {p:"¿Qué famoso inventor trabajó con corriente alterna?", o:["Nikola Tesla","Thomas Edison","Alexander Graham Bell","Benjamin Franklin"], r:"Nikola Tesla"},
  {p:"¿Qué equipo de fútbol americano universitario tiene más títulos nacionales?", o:["University of Alabama","Ohio State","Notre Dame","Michigan"], r:"University of Alabama"},
  {p:"¿Qué deporte tiene la NBA?", o:["Baloncesto","Fútbol americano","Béisbol","Hockey"], r:"Baloncesto"},
  {p:"¿Qué famoso equipo de béisbol juega en Fenway Park?", o:["Boston Red Sox","New York Yankees","Chicago Cubs","Los Angeles Dodgers"], r:"Boston Red Sox"},
  {p:"¿Qué equipo de hockey es famoso en EE.UU.?", o:["Chicago Blackhawks","Los Angeles Kings","New York Rangers","Boston Bruins"], r:"Chicago Blackhawks"},
  {p:"¿Qué deporte es el más visto en Super Bowl?", o:["Fútbol americano","Baloncesto","Béisbol","Hockey"], r:"Fútbol americano"},
  {p:"¿Qué famoso inventor estadounidense creó el teléfono?", o:["Alexander Graham Bell","Thomas Edison","Nikola Tesla","Samuel Morse"], r:"Alexander Graham Bell"},
  {p:"¿Qué famoso inventor creó la bombilla incandescente?", o:["Thomas Edison","Nikola Tesla","Benjamin Franklin","Alexander Graham Bell"], r:"Thomas Edison"},
  {p:"¿Qué equipo de la NFL ganó más Super Bowls?", o:["New England Patriots","Dallas Cowboys","Pittsburgh Steelers","San Francisco 49ers"], r:"New England Patriots"},
  {p:"¿Qué famoso boxeador fue conocido como 'The Greatest'?", o:["Muhammad Ali","Mike Tyson","Joe Frazier","George Foreman"], r:"Muhammad Ali"},
  {p:"¿Qué deporte se practica en el Madison Square Garden?", o:["Baloncesto y Hockey","Fútbol","Béisbol","Fútbol americano"], r:"Baloncesto y Hockey"},
  {p:"¿Qué equipo de béisbol juega en Wrigley Field?", o:["Chicago Cubs","Boston Red Sox","New York Yankees","Los Angeles Dodgers"], r:"Chicago Cubs"},
  {p:"¿Qué famoso luchador WWE fue conocido como Hulk Hogan?", o:["Hulk Hogan","The Rock","Stone Cold Steve Austin","John Cena"], r:"Hulk Hogan"},
  {p:"¿Qué equipo de la NBA es conocido como los Celtics?", o:["Boston Celtics","Los Angeles Lakers","Chicago Bulls","Miami Heat"], r:"Boston Celtics"},
  {p:"¿Qué inventor estadounidense fundó General Electric?", o:["Thomas Edison","Nikola Tesla","Alexander Graham Bell","Benjamin Franklin"], r:"Thomas Edison"},
  {p:"¿Qué deporte tiene la liga MLB?", o:["Béisbol","Fútbol americano","Baloncesto","Hockey"], r:"Béisbol"},
  {p:"¿Qué famoso boxeador peleó contra Evander Holyfield?", o:["Mike Tyson","Muhammad Ali","George Foreman","Joe Frazier"], r:"Mike Tyson"},
  {p:"¿Qué famoso invento es atribuido a Thomas Edison?", o:["Bombilla","Teléfono","Radio","Computadora"], r:"Bombilla"},
  {p:"¿Qué famoso científico trabajó con la corriente alterna?", o:["Nikola Tesla","Thomas Edison","Alexander Graham Bell","Benjamin Franklin"], r:"Nikola Tesla"},
  {p:"¿Qué equipo de la NFL juega en Green Bay?", o:["Green Bay Packers","Dallas Cowboys","New England Patriots","San Francisco 49ers"], r:"Green Bay Packers"},
  {p:"¿Qué famoso inventor inventó el fonógrafo?", o:["Thomas Edison","Alexander Graham Bell","Nikola Tesla","Benjamin Franklin"], r:"Thomas Edison"},
  {p:"¿Qué equipo de baloncesto juega en Miami?", o:["Miami Heat","Los Angeles Lakers","Boston Celtics","Chicago Bulls"], r:"Miami Heat"},
  {p:"¿Qué famoso luchador WWE fue conocido como John Cena?", o:["John Cena","The Rock","Stone Cold Steve Austin","Hulk Hogan"], r:"John Cena"},
  {p:"¿Qué equipo de béisbol juega en Los Ángeles Dodgers?", o:["Los Angeles Dodgers","New York Yankees","Boston Red Sox","Chicago Cubs"], r:"Los Angeles Dodgers"},
  {p:"¿Qué inventor trabajó en el telégrafo?", o:["Samuel Morse","Thomas Edison","Nikola Tesla","Alexander Graham Bell"], r:"Samuel Morse"},
  {p:"¿Qué deporte tiene la liga UFC?", o:["Artes Marciales Mixtas","Fútbol","Baloncesto","Béisbol"], r:"Artes Marciales Mixtas"},
  {p:"¿Qué famoso inventor estadounidense es conocido por el telégrafo?", o:["Samuel Morse","Thomas Edison","Nikola Tesla","Alexander Graham Bell"], r:"Samuel Morse"},
  {p:"¿Qué equipo de hockey juega en Boston?", o:["Boston Bruins","Chicago Blackhawks","New York Rangers","Los Angeles Kings"], r:"Boston Bruins"},
  {p:"¿Qué famoso inventor estadounidense trabajó en la lámpara incandescente?", o:["Thomas Edison","Nikola Tesla","Alexander Graham Bell","Benjamin Franklin"], r:"Thomas Edison"},
  {p:"¿Qué famoso boxeador fue apodado 'Buster Douglas'?", o:["Buster Douglas","Muhammad Ali","Mike Tyson","George Foreman"], r:"Buster Douglas"},
  {p:"¿Qué equipo de fútbol americano juega en Pittsburgh?", o:["Pittsburgh Steelers","Dallas Cowboys","New England Patriots","Green Bay Packers"], r:"Pittsburgh Steelers"},
  {p:"¿Qué famoso inventor inventó la corriente alterna?", o:["Nikola Tesla","Thomas Edison","Alexander Graham Bell","Benjamin Franklin"], r:"Nikola Tesla"},
  {p:"¿Qué equipo de baloncesto juega en Golden State?", o:["Golden State Warriors","Los Angeles Lakers","Chicago Bulls","Boston Celtics"], r:"Golden State Warriors"},
  {p:"¿Qué famoso boxeador peleó contra Mike Tyson y ganó en 1990?", o:["Buster Douglas","Muhammad Ali","Evander Holyfield","George Foreman"], r:"Buster Douglas"},
  {p:"¿Qué equipo de NFL juega en San Francisco?", o:["San Francisco 49ers","Dallas Cowboys","New England Patriots","Green Bay Packers"], r:"San Francisco 49ers"},
  {p:"¿Qué equipo de la NBA tiene LeBron James como ícono?", o:["Los Angeles Lakers","Chicago Bulls","Boston Celtics","Miami Heat"], r:"Los Angeles Lakers"},
  {p:"¿Qué famoso luchador WWE fue conocido como 'Stone Cold'?", o:["Stone Cold Steve Austin","The Rock","John Cena","Hulk Hogan"], r:"Stone Cold Steve Austin"},
  {p:"¿Qué equipo de béisbol juega en Arizona?", o:["Arizona Diamondbacks","Los Angeles Dodgers","Boston Red Sox","New York Yankees"], r:"Arizona Diamondbacks"},
  {p:"¿Qué famoso inventor inventó el teléfono y el fotófono?", o:["Alexander Graham Bell","Thomas Edison","Nikola Tesla","Samuel Morse"], r:"Alexander Graham Bell"},
  {p:"¿Qué equipo de la NBA juega en Brooklyn?", o:["Brooklyn Nets","Los Angeles Lakers","Boston Celtics","Chicago Bulls"], r:"Brooklyn Nets"},
  {p:"¿Qué equipo de fútbol americano juega en New England?", o:["New England Patriots","Dallas Cowboys","Green Bay Packers","San Francisco 49ers"], r:"New England Patriots"},
  {p:"¿Qué equipo de béisbol juega en Cleveland?", o:["Cleveland Guardians","Boston Red Sox","Chicago Cubs","Los Angeles Dodgers"], r:"Cleveland Guardians"},
  {p:"¿Qué famoso boxeador es conocido por su apodo 'The Greatest'?", o:["Muhammad Ali","Mike Tyson","Evander Holyfield","George Foreman"], r:"Muhammad Ali"},
  {p:"¿Qué equipo de la NBA juega en Dallas?", o:["Dallas Mavericks","Los Angeles Lakers","Boston Celtics","Chicago Bulls"], r:"Dallas Mavericks"},
  {p:"¿Qué famoso invento es de Nikola Tesla y usado en electricidad?", o:["Corriente alterna","Bombilla","Teléfono","Telégrafo"], r:"Corriente alterna"},
  {p:"¿Qué equipo de la NFL juega en Miami?", o:["Miami Dolphins","Dallas Cowboys","Green Bay Packers","New England Patriots"], r:"Miami Dolphins"}
];
