const preguntasBiblia = [
  {p:"¿Quién construyó el arca?", o:["Noé","Moisés","Abraham","David"], r:"Noé"},
  {p:"¿Quién fue arrojado al foso de los leones?", o:["Daniel","José","Jonás","Elías"], r:"Daniel"},
  {p:"¿Quién recibió los Diez Mandamientos?", o:["Moisés","Abraham","David","Jesús"], r:"Moisés"},
  {p:"¿Quién traicionó a Jesús por 30 piezas de plata?", o:["Judas Iscariote","Pedro","Juan","Tomás"], r:"Judas Iscariote"},
  {p:"¿Quién fue el primer hombre creado según la Biblia?", o:["Adán","Noé","Moisés","Abraham"], r:"Adán"},
  {p:"¿Quién fue la madre de Jesús?", o:["María","Marta","Isabel","Rebeca"], r:"María"},
  {p:"¿Cuántos días y noches llovió durante el diluvio?", o:["40","30","50","20"], r:"40"},
  {p:"¿Qué profeta fue llevado al cielo en un carro de fuego?", o:["Elías","Eliseo","Isaías","Jeremías"], r:"Elías"},
  {p:"¿Quién fue vendido como esclavo por sus hermanos?", o:["José","Jacob","Esau","Moisés"], r:"José"},
  {p:"¿Qué mar se dividió para que los israelitas cruzaran?", o:["Mar Rojo","Mar Muerto","Mar Mediterráneo","Mar de Galilea"], r:"Mar Rojo"},
  {p:"¿Quién fue el rey que construyó el Templo en Jerusalén?", o:["Salomón","David","Saúl","Ezequías"], r:"Salomón"},
  {p:"¿Quién derrotó a Goliat?", o:["David","Saúl","Josué","Ezequías"], r:"David"},
  {p:"¿Quién escribió la mayoría de los Salmos?", o:["David","Moisés","Salomón","Isaías"], r:"David"},
  {p:"¿Cuál es el primer libro de la Biblia?", o:["Génesis","Éxodo","Levítico","Números"], r:"Génesis"},
  {p:"¿Quién fue el profeta que desafió a los profetas de Baal?", o:["Elías","Isaías","Jeremías","Ezequiel"], r:"Elías"},
  {p:"¿Qué gigante fue vencido por un joven pastor?", o:["Goliat","Saúl","Nabal","Og"], r:"Goliat"},
  {p:"¿Quién interpretó los sueños del faraón en Egipto?", o:["José","Moisés","Daniel","Salomón"], r:"José"},
  {p:"¿Qué discípulo negó a Jesús tres veces?", o:["Pedro","Juan","Santiago","Andrés"], r:"Pedro"},
  {p:"¿Quién fue lanzado al mar y tragado por un gran pez?", o:["Jonás","Elías","Moisés","Abraham"], r:"Jonás"},
  {p:"¿Quién fue el padre de Isaac?", o:["Abraham","Jacob","Noé","Moisés"], r:"Abraham"},
  {p:"¿Quién fue la esposa de Abraham?", o:["Sara","Rebeca","Raquel","Lea"], r:"Sara"},
  {p:"¿Quién fue el hermano de Moisés y sumo sacerdote?", o:["Aarón","Josué","Caleb","Elías"], r:"Aarón"},
  {p:"¿Quién escribió el libro de Apocalipsis?", o:["Juan","Pedro","Pablo","Moisés"], r:"Juan"},
  {p:"¿Cuál es el mandamiento principal según Jesús?", o:["Amar a Dios y al prójimo","No matarás","No robarás","Honra a tu padre y madre"], r:"Amar a Dios y al prójimo"},
  {p:"¿Qué apóstol escribió muchas cartas en el Nuevo Testamento?", o:["Pablo","Pedro","Juan","Jacobo"], r:"Pablo"},
  {p:"¿Qué alimento comió el pueblo de Israel en el desierto?", o:["Maná","Pan","Carne","Miel"], r:"Maná"},
  {p:"¿Qué juez derribó los pilares del templo de los filisteos?", o:["Sansón","Gedeón","Samuel","Elías"], r:"Sansón"},
  {p:"¿Quién fue el profeta que llamó a Israel al arrepentimiento con visiones de huesos secos?", o:["Ezequiel","Isaías","Jeremías","Daniel"], r:"Ezequiel"},
  {p:"¿Qué ciudad fue destruida por fuego y azufre por su pecado?", o:["Sodoma","Jericó","Babel","Nínive"], r:"Sodoma"},
  {p:"¿Quién fue liberado de la cárcel con la ayuda de un ángel?", o:["Pedro","Pablo","Juan","Moisés"], r:"Pedro"},
  {p:"¿Qué rey fue conocido por su gran sabiduría?", o:["Salomón","David","Saúl","Ezequías"], r:"Salomón"},
  {p:"¿Qué apóstol escribió el Evangelio que lleva su nombre?", o:["Juan","Mateo","Lucas","Marcos"], r:"Juan"},
  {p:"¿Qué discípulo fue pescador antes de seguir a Jesús?", o:["Pedro","Juan","Mateo","Tomás"], r:"Pedro"},
  {p:"¿Quién escribió el libro de Job?", o:["Job","Moisés","David","Salomón"], r:"Job"},
  {p:"¿Quién fue el profeta que desafió a los reyes de Israel y predijo sequía?", o:["Elías","Isaías","Jeremías","Oseas"], r:"Elías"},
  {p:"¿Qué mujer se convirtió en estatua de sal?", o:["La esposa de Lot","Sara","Rebeca","Raquel"], r:"La esposa de Lot"},
  {p:"¿Quién fue la madre de Samuel?", o:["Ana","Sara","Rebeca","Raquel"], r:"Ana"},
  {p:"¿Quién fue el líder que guió a Israel a la Tierra Prometida?", o:["Josué","Moisés","David","Gedeón"], r:"Josué"},
  {p:"¿Qué apóstol escribió el Evangelio según Mateo?", o:["Mateo","Juan","Lucas","Marcos"], r:"Mateo"},
  {p:"¿Quién fue el profeta que confrontó al rey Acab y Jezabel?", o:["Elías","Isaías","Jeremías","Jonás"], r:"Elías"},
  {p:"¿Qué discípulo dudó de la resurrección de Jesús hasta ver las heridas?", o:["Tomás","Pedro","Juan","Santiago"], r:"Tomás"},
  {p:"¿Qué apóstol fue conocido como el 'apóstol de los gentiles'?", o:["Pablo","Pedro","Juan","Jacobo"], r:"Pablo"},
  {p:"¿Quién fue la esposa de Isaac?", o:["Rebeca","Sara","Raquel","Lea"], r:"Rebeca"},
  {p:"¿Qué ciudad cayó cuando los muros se derrumbaron con trompetas?", o:["Jericó","Sodoma","Babel","Nínive"], r:"Jericó"},
  {p:"¿Quién fue el profeta que subió al cielo en un torbellino?", o:["Elías","Eliseo","Isaías","Jeremías"], r:"Elías"},
  {p:"¿Qué rey fue conocido por escribir proverbios?", o:["Salomón","David","Saúl","Ezequías"], r:"Salomón"},
  {p:"¿Qué apóstol escribió el Evangelio según Lucas?", o:["Lucas","Juan","Mateo","Marcos"], r:"Lucas"},
  {p:"¿Quién fue liberado de la prisión después de orar y cantar himnos?", o:["Pedro","Pablo","Juan","Moisés"], r:"Pedro"},
  {p:"¿Qué profeta recibió visiones de huesos secos?", o:["Ezequiel","Isaías","Jeremías","Daniel"], r:"Ezequiel"},
  {p:"¿Quién fue el primer rey de Israel?", o:["Saúl","David","Salomón","Ezequías"], r:"Saúl"},
  {p:"¿Qué apóstol escribió el Evangelio según Marcos?", o:["Marcos","Juan","Mateo","Lucas"], r:"Marcos"},
  {p:"¿Quién fue el profeta que sobrevivió a la cueva de leones?", o:["Daniel","José","Jonás","Elías"], r:"Daniel"},
  {p:"¿Qué mujer judía salvó a su pueblo del exterminio?", o:["Ester","Miriam","Débora","Ruth"], r:"Ester"},
  {p:"¿Quién fue el padre de Juan el Bautista?", o:["Zacarías","Moisés","Abraham","David"], r:"Zacarías"},
  {p:"¿Qué apóstol fue crucificado cabeza abajo?", o:["Pedro","Juan","Jacobo","Andrés"], r:"Pedro"},
  {p:"¿Qué profeta fue conocido por su paciencia y sufrimiento?", o:["Job","Moisés","David","Salomón"], r:"Job"},
  {p:"¿Qué discípulo escribió el Evangelio según Juan?", o:["Juan","Mateo","Lucas","Marcos"], r:"Juan"},
  {p:"¿Qué mujer se convirtió en madre de Samuel tras rezar mucho?", o:["Ana","Sara","Rebeca","Raquel"], r:"Ana"},
  {p:"¿Qué rey construyó un templo en Jerusalén?", o:["Salomón","David","Saúl","Ezequías"], r:"Salomón"},
  {p:"¿Quién fue el profeta que predijo el nacimiento de Jesús?", o:["Isaías","Jeremías","Daniel","Elías"], r:"Isaías"},
  {p:"¿Qué discípulo fue conocido como el hermano de Pedro?", o:["Andrés","Juan","Jacobo","Tomás"], r:"Andrés"},
  {p:"¿Qué profeta fue tragado por un gran pez?", o:["Jonás","Moisés","Elías","Daniel"], r:"Jonás"},
  {p:"¿Quién interpretó los sueños del faraón en Egipto?", o:["José","Moisés","Daniel","Salomón"], r:"José"},
  {p:"¿Qué apóstol escribió muchas cartas a las iglesias?", o:["Pablo","Pedro","Juan","Jacobo"], r:"Pablo"},
  {p:"¿Qué profeta fue conocido por desafiar a los profetas de Baal?", o:["Elías","Isaías","Jeremías","Oseas"], r:"Elías"},
  {p:"¿Quién fue la madre de Samuel?", o:["Ana","Sara","Rebeca","Raquel"], r:"Ana"},
  {p:"¿Qué apóstol fue conocido como el 'apóstol dudoso'?", o:["Tomás","Pedro","Juan","Jacobo"], r:"Tomás"},
  {p:"¿Quién fue el padre de Isaac?", o:["Abraham","Jacob","Moisés","Noé"], r:"Abraham"},
  {p:"¿Qué ciudad fue destruida por fuego y azufre?", o:["Sodoma","Jericó","Babel","Nínive"], r:"Sodoma"},
  {p:"¿Quién fue el rey que escribió la mayoría de los proverbios?", o:["Salomón","David","Saúl","Ezequías"], r:"Salomón"},
  {p:"¿Qué apóstol fue conocido como 'el amado'?", o:["Juan","Pedro","Santiago","Andrés"], r:"Juan"},
  {p:"¿Quién fue arrojado al foso de los leones?", o:["Daniel","José","Jonás","Elías"], r:"Daniel"},
  {p:"¿Quién construyó el arca para el diluvio?", o:["Noé","Moisés","Abraham","David"], r:"Noé"},
  {p:"¿Qué discípulo negó a Jesús tres veces?", o:["Pedro","Juan","Santiago","Andrés"], r:"Pedro"},
  {p:"¿Quién fue traicionado por 30 piezas de plata?", o:["Judas Iscariote","Pedro","Juan","Tomás"], r:"Judas Iscariote"},
  {p:"¿Qué rey fue conocido por su gran sabiduría?", o:["Salomón","David","Saúl","Ezequías"], r:"Salomón"},
  {p:"¿Qué profeta recibió visiones de huesos secos?", o:["Ezequiel","Isaías","Jeremías","Daniel"], r:"Ezequiel"},
  {p:"¿Qué mujer salvó a su pueblo de Hamán?", o:["Ester","Miriam","Débora","Ruth"], r:"Ester"},
  {p:"¿Quién fue el padre de Juan el Bautista?", o:["Zacarías","Moisés","Abraham","David"], r:"Zacarías"},
  {p:"¿Quién fue llevado al cielo en un carro de fuego?", o:["Elías","Eliseo","Isaías","Jeremías"], r:"Elías"},
  {p:"¿Qué profeta desafió a los reyes de Israel y Jezabel?", o:["Elías","Isaías","Jeremías","Jonás"], r:"Elías"},
  {p:"¿Qué ciudad cayó con el sonido de trompetas?", o:["Jericó","Sodoma","Babel","Nínive"], r:"Jericó"},
  {p:"¿Qué discípulo fue pescador antes de seguir a Jesús?", o:["Pedro","Juan","Mateo","Tomás"], r:"Pedro"},
  {p:"¿Qué apóstol escribió el libro de Apocalipsis?", o:["Juan","Pedro","Pablo","Moisés"], r:"Juan"},
  {p:"¿Quién interpretó los sueños en Babilonia?", o:["Daniel","José","Moisés","Salomón"], r:"Daniel"},
  {p:"¿Qué alimento comió el pueblo de Israel en el desierto?", o:["Maná","Pan","Carne","Miel"], r:"Maná"},
  {p:"¿Qué mujer se convirtió en estatua de sal?", o:["La esposa de Lot","Sara","Rebeca","Raquel"], r:"La esposa de Lot"},
  {p:"¿Quién fue liberado de la prisión con la ayuda de un ángel?", o:["Pedro","Pablo","Juan","Moisés"], r:"Pedro"},
  {p:"¿Quién fue el primer hombre creado?", o:["Adán","Noé","Moisés","Abraham"], r:"Adán"},
  {p:"¿Quién fue la madre de Jesús?", o:["María","Marta","Isabel","Rebeca"], r:"María"}
];
