const preguntasIngles = [
    { p: "¿Cómo se dice 'hola' en inglés?", o: ["Hello", "Hi", "Hey", "Hola"], r: "Hello" },
    { p: "¿Cómo se dice 'adiós' en inglés?", o: ["Goodbye", "Bye", "See you", "Adiós"], r: "Goodbye" },
    { p: "¿Cómo se dice 'gracias' en inglés?", o: ["Thanks", "Thank you", "Thx", "Gracias"], r: "Thank you" },
    { p: "¿Cómo se dice 'por favor' en inglés?", o: ["Please", "Por favor", "Plz", "Favor"], r: "Please" },
    { p: "¿Cómo se dice 'lo siento' en inglés?", o: ["Sorry", "Excuse me", "I am sorry", "Lo siento"], r: "Sorry" },
    { p: "¿Cómo se dice 'sí' en inglés?", o: ["Yes", "Yeah", "No", "Sí"], r: "Yes" },
    { p: "¿Cómo se dice 'no' en inglés?", o: ["No", "Not", "None", "No"], r: "No" },
    { p: "¿Cómo se dice 'buenos días' en inglés?", o: ["Good morning", "Good afternoon", "Good night", "Buenos días"], r: "Good morning" },
    { p: "¿Cómo se dice 'buenas noches' en inglés?", o: ["Good night", "Good evening", "Good morning", "Buenas noches"], r: "Good night" },
    { p: "¿Cómo se dice '¿Cómo estás?' en inglés?", o: ["How are you?", "How do you do?", "What is up?", "¿Cómo estás?"], r: "How are you?" },
    { p: "¿Cómo se dice 'bien' en inglés?", o: ["Good", "Fine", "Well", "Bien"], r: "Good" },
    { p: "¿Cómo se dice 'mal' en inglés?", o: ["Bad", "Wrong", "Poor", "Mal"], r: "Bad" },
    { p: "¿Cómo se dice 'amigo' en inglés?", o: ["Friend", "Mate", "Buddy", "Amigo"], r: "Friend" },
    { p: "¿Cómo se dice 'familia' en inglés?", o: ["Family", "Fam", "Relatives", "Familia"], r: "Family" },
    { p: "¿Cómo se dice 'escuela' en inglés?", o: ["School", "Class", "College", "Escuela"], r: "School" },
    { p: "¿Cómo se dice 'profesor' en inglés?", o: ["Teacher", "Professor", "Instructor", "Profesor"], r: "Teacher" },
    { p: "¿Cómo se dice 'libro' en inglés?", o: ["Book", "Magazine", "Notebook", "Libro"], r: "Book" },
    { p: "¿Cómo se dice 'pluma' en inglés?", o: ["Pen", "Pencil", "Marker", "Pluma"], r: "Pen" },
    { p: "¿Cómo se dice 'mesa' en inglés?", o: ["Table", "Desk", "Chair", "Mesa"], r: "Table" },
    { p: "¿Cómo se dice 'silla' en inglés?", o: ["Chair", "Seat", "Bench", "Silla"], r: "Chair" },
    { p: "¿Cómo se dice 'casa' en inglés?", o: ["House", "Home", "Building", "Casa"], r: "House" },
    { p: "¿Cómo se dice 'puerta' en inglés?", o: ["Door", "Gate", "Window", "Puerta"], r: "Door" },
    { p: "¿Cómo se dice 'ventana' en inglés?", o: ["Window", "Door", "Glass", "Ventana"], r: "Window" },
    { p: "¿Cómo se dice 'coche' en inglés?", o: ["Car", "Bus", "Truck", "Coche"], r: "Car" },
    { p: "¿Cómo se dice 'bicicleta' en inglés?", o: ["Bicycle", "Bike", "Cycle", "Bicicleta"], r: "Bicycle" },
    { p: "¿Cómo se dice 'perro' en inglés?", o: ["Dog", "Cat", "Pet", "Perro"], r: "Dog" },
    { p: "¿Cómo se dice 'gato' en inglés?", o: ["Cat", "Dog", "Kitten", "Gato"], r: "Cat" },
    { p: "¿Cómo se dice 'agua' en inglés?", o: ["Water", "Juice", "Milk", "Agua"], r: "Water" },
    { p: "¿Cómo se dice 'comida' en inglés?", o: ["Food", "Meal", "Snack", "Comida"], r: "Food" },
    { p: "¿Cómo se dice 'desayuno' en inglés?", o: ["Breakfast", "Lunch", "Dinner", "Desayuno"], r: "Breakfast" },
    { p: "¿Cómo se dice 'almuerzo' en inglés?", o: ["Lunch", "Dinner", "Snack", "Almuerzo"], r: "Lunch" },
    { p: "¿Cómo se dice 'cena' en inglés?", o: ["Dinner", "Lunch", "Supper", "Cena"], r: "Dinner" },
    { p: "¿Cómo se dice 'mañana' en inglés?", o: ["Morning", "Tomorrow", "Day", "Mañana"], r: "Morning" },
    { p: "¿Cómo se dice 'tarde' en inglés?", o: ["Afternoon", "Evening", "Late", "Tarde"], r: "Afternoon" },
    { p: "¿Cómo se dice 'noche' en inglés?", o: ["Night", "Evening", "Dark", "Noche"], r: "Night" },
    { p: "¿Cómo se dice 'hoy' en inglés?", o: ["Today", "Tomorrow", "Yesterday", "Hoy"], r: "Today" },
    { p: "¿Cómo se dice 'ayer' en inglés?", o: ["Yesterday", "Today", "Last day", "Ayer"], r: "Yesterday" },
    { p: "¿Cómo se dice 'mañana' (día siguiente) en inglés?", o: ["Tomorrow", "Today", "Next day", "Mañana"], r: "Tomorrow" },
    { p: "¿Cómo se dice 'rojo' en inglés?", o: ["Red", "Blue", "Green", "Rojo"], r: "Red" },
    { p: "¿Cómo se dice 'azul' en inglés?", o: ["Blue", "Red", "Green", "Azul"], r: "Blue" },
    { p: "¿Cómo se dice 'verde' en inglés?", o: ["Green", "Red", "Blue", "Verde"], r: "Green" },
    { p: "¿Cómo se dice 'amarillo' en inglés?", o: ["Yellow", "Green", "Orange", "Amarillo"], r: "Yellow" },
    { p: "¿Cómo se dice 'negro' en inglés?", o: ["Black", "White", "Gray", "Negro"], r: "Black" },
    { p: "¿Cómo se dice 'blanco' en inglés?", o: ["White", "Black", "Gray", "Blanco"], r: "White" },
    { p: "¿Cómo se dice 'grande' en inglés?", o: ["Big", "Small", "Large", "Grande"], r: "Big" },
    { p: "¿Cómo se dice 'pequeño' en inglés?", o: ["Small", "Big", "Little", "Pequeño"], r: "Small" },
    { p: "¿Cómo se dice 'rápido' en inglés?", o: ["Fast", "Slow", "Quick", "Rápido"], r: "Fast" },
    { p: "¿Cómo se dice 'lento' en inglés?", o: ["Slow", "Fast", "Sluggish", "Lento"], r: "Slow" },
    { p: "¿Cómo se dice 'feliz' en inglés?", o: ["Happy", "Sad", "Joyful", "Feliz"], r: "Happy" },
    { p: "¿Cómo se dice 'triste' en inglés?", o: ["Sad", "Happy", "Unhappy", "Triste"], r: "Sad" },
    { p: "¿Cómo se dice 'enojado' en inglés?", o: ["Angry", "Mad", "Upset", "Enojado"], r: "Angry" },
    { p: "¿Cómo se dice 'cansado' en inglés?", o: ["Tired", "Sleepy", "Exhausted", "Cansado"], r: "Tired" },
    { p: "¿Cómo se dice 'amable' en inglés?", o: ["Kind", "Nice", "Friendly", "Amable"], r: "Kind" },
    { p: "¿Cómo se dice 'fácil' en inglés?", o: ["Easy", "Hard", "Simple", "Fácil"], r: "Easy" },
    { p: "¿Cómo se dice 'difícil' en inglés?", o: ["Difficult", "Hard", "Tough", "Difícil"], r: "Difficult" },
    { p: "¿Cómo se dice 'nuevo' en inglés?", o: ["New", "Old", "Fresh", "Nuevo"], r: "New" },
    { p: "¿Cómo se dice 'viejo' en inglés?", o: ["Old", "New", "Ancient", "Viejo"], r: "Old" },
    { p: "¿Cómo se dice 'frío' en inglés?", o: ["Cold", "Hot", "Cool", "Frío"], r: "Cold" },
    { p: "¿Cómo se dice 'caliente' en inglés?", o: ["Hot", "Warm", "Cold", "Caliente"], r: "Hot" },
    { p: "¿Cómo se dice 'lluvia' en inglés?", o: ["Rain", "Snow", "Storm", "Lluvia"], r: "Rain" },
    { p: "¿Cómo se dice 'sol' en inglés?", o: ["Sun", "Moon", "Star", "Sol"], r: "Sun" },
    { p: "¿Cómo se dice 'luna' en inglés?", o: ["Moon", "Sun", "Star", "Luna"], r: "Moon" },
    { p: "¿Cómo se dice 'estrella' en inglés?", o: ["Star", "Sun", "Moon", "Estrella"], r: "Star" },
    { p: "¿Cómo se dice 'cielo' en inglés?", o: ["Sky", "Cloud", "Heaven", "Cielo"], r: "Sky" },
    { p: "¿Cómo se dice 'tierra' en inglés?", o: ["Earth", "Ground", "Land", "Tierra"], r: "Earth" },
    { p: "¿Cómo se dice 'mar' en inglés?", o: ["Sea", "Ocean", "Lake", "Mar"], r: "Sea" },
    { p: "¿Cómo se dice 'río' en inglés?", o: ["River", "Stream", "Lake", "Río"], r: "River" },
    { p: "¿Cómo se dice 'montaña' en inglés?", o: ["Mountain", "Hill", "Peak", "Montaña"], r: "Mountain" },
    { p: "¿Cómo se dice 'bosque' en inglés?", o: ["Forest", "Jungle", "Wood", "Bosque"], r: "Forest" },
    { p: "¿Cómo se dice 'ciudad' en inglés?", o: ["City", "Town", "Village", "Ciudad"], r: "City" },
    { p: "¿Cómo se dice 'pueblo' en inglés?", o: ["Town", "City", "Village", "Pueblo"], r: "Town" },
    { p: "¿Cómo se dice 'país' en inglés?", o: ["Country", "Nation", "State", "País"], r: "Country" },
    { p: "¿Cómo se dice 'continente' en inglés?", o: ["Continent", "Region", "Land", "Continente"], r: "Continent" },
    { p: "¿Cómo se dice 'lago' en inglés?", o: ["Lake", "Pond", "River", "Lago"], r: "Lake" },
    { p: "¿Cómo se dice 'playa' en inglés?", o: ["Beach", "Shore", "Seaside", "Playa"], r: "Beach" },
    { p: "¿Cómo se dice 'isla' en inglés?", o: ["Island", "Isle", "Atoll", "Isla"], r: "Island" },
    { p: "¿Cómo se dice 'sol' en inglés?", o: ["Sun", "Moon", "Star", "Sol"], r: "Sun" },
    { p: "¿Cómo se dice 'nube' en inglés?", o: ["Cloud", "Fog", "Mist", "Nube"], r: "Cloud" },
    { p: "¿Cómo se dice 'lluvioso' en inglés?", o: ["Rainy", "Sunny", "Windy", "Stormy"], r: "Rainy" },
    { p: "¿Cómo se dice 'ventoso' en inglés?", o: ["Windy", "Breezy", "Stormy", "Calm"], r: "Windy" },
    { p: "¿Cómo se dice 'calmado' en inglés?", o: ["Calm", "Quiet", "Still", "Peaceful"], r: "Calm" },
    { p: "¿Cómo se dice 'ruidoso' en inglés?", o: ["Noisy", "Loud", "Busy", "Ruidoso"], r: "Noisy" },
    { p: "¿Cómo se dice 'fácil' en inglés?", o: ["Easy", "Simple", "Clear", "Fácil"], r: "Easy" },
    { p: "¿Cómo se dice 'difícil' en inglés?", o: ["Difficult", "Hard", "Tough", "Difícil"], r: "Difficult" },
];
