const preguntasProgramacion = [
  // 1-10
  { categoria: "Programación", pregunta: "¿Qué es hardware?", opciones: ["Componentes físicos de la computadora", "Software", "Lenguaje de programación", "Base de datos"], respuesta: "Componentes físicos de la computadora" },
  { categoria: "Programación", pregunta: "¿Qué es software?", opciones: ["Programas y aplicaciones", "Componentes físicos", "Redes", "Lenguajes de marcado"], respuesta: "Programas y aplicaciones" },
  { categoria: "Programación", pregunta: "¿Cuál es un lenguaje de programación?", opciones: ["Python", "Word", "Windows", "Excel"], respuesta: "Python" },
  { categoria: "Programación", pregunta: "¿Qué es una variable en programación?", opciones: ["Espacio de memoria que almacena datos", "Un programa completo", "Un hardware", "Un sistema operativo"], respuesta: "Espacio de memoria que almacena datos" },
  { categoria: "Programación", pregunta: "¿Qué es un bucle 'for'?", opciones: ["Repetición controlada por contador", "Condición lógica", "Función matemática", "Variable"], respuesta: "Repetición controlada por contador" },
  { categoria: "Programación", pregunta: "¿Qué es un bucle 'while'?", opciones: ["Repetición mientras la condición sea verdadera", "Declaración de variable", "Condición falsa", "Compilador"], respuesta: "Repetición mientras la condición sea verdadera" },
  { categoria: "Programación", pregunta: "¿Qué es un compilador?", opciones: ["Programa que traduce código a lenguaje máquina", "Lenguaje de programación", "Base de datos", "Sistema operativo"], respuesta: "Programa que traduce código a lenguaje máquina" },
  { categoria: "Programación", pregunta: "¿Qué es una función en programación?", opciones: ["Bloque de código reutilizable", "Hardware", "Sistema operativo", "Variable"], respuesta: "Bloque de código reutilizable" },
  { categoria: "Programación", pregunta: "¿Qué es un arreglo (array)?", opciones: ["Colección de elementos del mismo tipo", "Variable individual", "Programa completo", "Red de computadoras"], respuesta: "Colección de elementos del mismo tipo" },
  { categoria: "Programación", pregunta: "¿Qué es un algoritmo?", opciones: ["Conjunto de pasos para resolver un problema", "Un hardware", "Un lenguaje", "Una variable"], respuesta: "Conjunto de pasos para resolver un problema" },

  // 11-20
  { categoria: "Programación", pregunta: "¿Qué es un sistema operativo?", opciones: ["Software que gestiona recursos del hardware", "Lenguaje de programación", "Base de datos", "Algoritmo"], respuesta: "Software que gestiona recursos del hardware" },
  { categoria: "Programación", pregunta: "¿Qué es un IDE?", opciones: ["Entorno de desarrollo integrado", "Lenguaje de programación", "Variable global", "Bucle"], respuesta: "Entorno de desarrollo integrado" },
  { categoria: "Programación", pregunta: "¿Qué es una condición 'if'?", opciones: ["Estructura de decisión", "Bucle", "Variable", "Base de datos"], respuesta: "Estructura de decisión" },
  { categoria: "Programación", pregunta: "¿Qué es un puntero en C/C++?", opciones: ["Variable que almacena la dirección de otra variable", "Bucle", "Función", "Array"], respuesta: "Variable que almacena la dirección de otra variable" },
  { categoria: "Programación", pregunta: "¿Qué significa HTML?", opciones: ["HyperText Markup Language", "High Transfer Machine Language", "Hyper Terminal Markup Language", "Hardware Text Main Language"], respuesta: "HyperText Markup Language" },
  { categoria: "Programación", pregunta: "¿Qué significa CSS?", opciones: ["Cascading Style Sheets", "Computer Style System", "Code Syntax Script", "Central Software Sheet"], respuesta: "Cascading Style Sheets" },
  { categoria: "Programación", pregunta: "¿Qué es una base de datos?", opciones: ["Colección organizada de datos", "Hardware", "Lenguaje de programación", "Variable"], respuesta: "Colección organizada de datos" },
  { categoria: "Programación", pregunta: "¿Qué es SQL?", opciones: ["Lenguaje para manejar bases de datos", "Lenguaje de programación general", "Sistema operativo", "Software de edición"], respuesta: "Lenguaje para manejar bases de datos" },
  { categoria: "Programación", pregunta: "¿Qué es la programación orientada a objetos?", opciones: ["Paradigma que usa clases y objetos", "Bucle infinito", "Variable global", "Algoritmo secuencial"], respuesta: "Paradigma que usa clases y objetos" },
  { categoria: "Programación", pregunta: "¿Qué es encapsulación?", opciones: ["Ocultar la información interna de un objeto", "Repetir un bucle", "Declarar variable", "Compilar código"], respuesta: "Ocultar la información interna de un objeto" },

  // 21-30
  { categoria: "Programación", pregunta: "¿Qué es herencia en programación?", opciones: ["Permite que una clase adquiera propiedades de otra", "Bucle 'for'", "Variable local", "Función matemática"], respuesta: "Permite que una clase adquiera propiedades de otra" },
  { categoria: "Programación", pregunta: "¿Qué es polimorfismo?", opciones: ["Capacidad de un objeto de tomar muchas formas", "Variable global", "Array", "Base de datos"], respuesta: "Capacidad de un objeto de tomar muchas formas" },
  { categoria: "Programación", pregunta: "¿Qué es un API?", opciones: ["Interfaz que permite interactuar con otro software", "Variable", "Bucle", "Compilador"], respuesta: "Interfaz que permite interactuar con otro software" },
  { categoria: "Programación", pregunta: "¿Qué es un bug?", opciones: ["Error en el código", "Bucle", "Variable", "Función"], respuesta: "Error en el código" },
  { categoria: "Programación", pregunta: "¿Qué es debugging?", opciones: ["Proceso de encontrar y corregir errores", "Compilar código", "Declarar variables", "Bucle"], respuesta: "Proceso de encontrar y corregir errores" },
  { categoria: "Programación", pregunta: "¿Qué es un lenguaje interpretado?", opciones: ["Se ejecuta línea por línea sin compilar", "Se compila antes de ejecutar", "Es hardware", "Es base de datos"], respuesta: "Se ejecuta línea por línea sin compilar" },
  { categoria: "Programación", pregunta: "¿Qué es un lenguaje compilado?", opciones: ["Se traduce a código máquina antes de ejecutar", "Se ejecuta línea por línea", "Es hardware", "Es un bug"], respuesta: "Se traduce a código máquina antes de ejecutar" },
  { categoria: "Programación", pregunta: "¿Qué es Git?", opciones: ["Sistema de control de versiones", "Lenguaje de programación", "Bucle", "Variable"], respuesta: "Sistema de control de versiones" },
  { categoria: "Programación", pregunta: "¿Qué es GitHub?", opciones: ["Plataforma para alojar repositorios Git", "Lenguaje de programación", "Bucle", "Variable"], respuesta: "Plataforma para alojar repositorios Git" },
  { categoria: "Programación", pregunta: "¿Qué es una variable local?", opciones: ["Se declara dentro de una función y solo existe ahí", "Se puede usar en todo el programa", "Es un tipo de hardware", "Es un bug"], respuesta: "Se declara dentro de una función y solo existe ahí" },

  // 31-40
  { categoria: "Programación", pregunta: "¿Qué es una variable global?", opciones: ["Se puede usar en cualquier parte del programa", "Solo existe dentro de una función", "Es un bug", "Es un array"], respuesta: "Se puede usar en cualquier parte del programa" },
  { categoria: "Programación", pregunta: "¿Qué es una constante?", opciones: ["Valor que no cambia durante la ejecución", "Variable mutable", "Bucle", "Función"], respuesta: "Valor que no cambia durante la ejecución" },
  { categoria: "Programación", pregunta: "¿Qué es un operador lógico?", opciones: ["AND, OR, NOT", "+, -, *, /", "%, ^, &", "int, float, string"], respuesta: "AND, OR, NOT" },
  { categoria: "Programación", pregunta: "¿Qué es un array multidimensional?", opciones: ["Array dentro de otro array", "Variable simple", "Bucle", "Función"], respuesta: "Array dentro de otro array" },
  { categoria: "Programación", pregunta: "¿Qué es un stack (pila) en estructuras de datos?", opciones: ["Estructura LIFO", "Estructura FIFO", "Variable", "Array simple"], respuesta: "Estructura LIFO" },
  { categoria: "Programación", pregunta: "¿Qué es una queue (cola) en estructuras de datos?", opciones: ["Estructura FIFO", "Estructura LIFO", "Variable", "Array simple"], respuesta: "Estructura FIFO" },
  { categoria: "Programación", pregunta: "¿Qué es recursividad?", opciones: ["Una función que se llama a sí misma", "Bucle 'for'", "Variable global", "Clase"], respuesta: "Una función que se llama a sí misma" },
  { categoria: "Programación", pregunta: "¿Qué es un IDE popular para Python?", opciones: ["PyCharm", "Visual Studio Code", "NetBeans", "Eclipse"], respuesta: "PyCharm" },
  { categoria: "Programación", pregunta: "¿Qué es un IDE popular para Java?", opciones: ["IntelliJ IDEA", "PyCharm", "Sublime Text", "Notepad"], respuesta: "IntelliJ IDEA" },
  { categoria: "Programación", pregunta: "¿Qué es un framework?", opciones: ["Conjunto de herramientas y librerías para desarrollar software", "Lenguaje de programación", "Hardware", "Bucle"], respuesta: "Conjunto de herramientas y librerías para desarrollar software" },

  // 41-50
  { categoria: "Programación", pregunta: "¿Qué es una librería (library)?", opciones: ["Código reutilizable para realizar tareas comunes", "Variable", "Bucle", "Sistema operativo"], respuesta: "Código reutilizable para realizar tareas comunes" },
  { categoria: "Programación", pregunta: "¿Qué es un IDE de JavaScript?", opciones: ["Visual Studio Code", "PyCharm", "IntelliJ", "Eclipse"], respuesta: "Visual Studio Code" },
  { categoria: "Programación", pregunta: "¿Qué es Node.js?", opciones: ["Entorno de ejecución para JavaScript", "Lenguaje de programación", "Base de datos", "Sistema operativo"], respuesta: "Entorno de ejecución para JavaScript" },
  { categoria: "Programación", pregunta: "¿Qué es React.js?", opciones: ["Librería de JavaScript para interfaces de usuario", "Lenguaje de programación", "Sistema operativo", "Base de datos"], respuesta: "Librería de JavaScript para interfaces de usuario" },
  { categoria: "Programación", pregunta: "¿Qué es un servidor web?", opciones: ["Programa que responde a solicitudes HTTP", "Lenguaje de programación", "Bucle", "Variable"], respuesta: "Programa que responde a solicitudes HTTP" },
  { categoria: "Programación", pregunta: "¿Qué es HTTP?", opciones: ["Protocolo de transferencia de hipertexto", "Lenguaje de programación", "Variable", "Base de datos"], respuesta: "Protocolo de transferencia de hipertexto" },
  { categoria: "Programación", pregunta: "¿Qué es HTTPS?", opciones: ["HTTP seguro con cifrado SSL/TLS", "Lenguaje de programación", "Bucle", "Variable"], respuesta: "HTTP seguro con cifrado SSL/TLS" },
  { categoria: "Programación", pregunta: "¿Qué es JSON?", opciones: ["Formato de intercambio de datos", "Lenguaje de programación", "Sistema operativo", "Variable"], respuesta: "Formato de intercambio de datos" },
  { categoria: "Programación", pregunta: "¿Qué es XML?", opciones: ["Lenguaje de marcado extensible", "Lenguaje de programación", "Variable", "Hardware"], respuesta: "Lenguaje de marcado extensible" },
  { categoria: "Programación", pregunta: "¿Qué es un servidor de base de datos?", opciones: ["Software que gestiona bases de datos", "Lenguaje de programación", "Variable", "Bucle"], respuesta: "Software que gestiona bases de datos" },

  // 51-60
  { categoria: "Programación", pregunta: "¿Qué es SQL Injection?", opciones: ["Ataque que inserta código malicioso en consultas SQL", "Variable global", "Bucle infinito", "Función matemática"], respuesta: "Ataque que inserta código malicioso en consultas SQL" },
  { categoria: "Programación", pregunta: "¿Qué es un IDE de C++?", opciones: ["Code::Blocks", "PyCharm", "Visual Studio Code", "IntelliJ IDEA"], respuesta: "Code::Blocks" },
  { categoria: "Programación", pregunta: "¿Qué es un compilador de C++?", opciones: ["Programa que convierte código C++ a lenguaje máquina", "Variable", "Bucle", "Base de datos"], respuesta: "Programa que convierte código C++ a lenguaje máquina" },
  { categoria: "Programación", pregunta: "¿Qué es JavaScript?", opciones: ["Lenguaje de programación interpretado", "Hardware", "Sistema operativo", "Base de datos"], respuesta: "Lenguaje de programación interpretado" },
  { categoria: "Programación", pregunta: "¿Qué es una interfaz en programación?", opciones: ["Definición de métodos que una clase debe implementar", "Variable", "Bucle", "Hardware"], respuesta: "Definición de métodos que una clase debe implementar" },
  { categoria: "Programación", pregunta: "¿Qué es UML?", opciones: ["Lenguaje de modelado unificado", "Lenguaje de programación", "Hardware", "Base de datos"], respuesta: "Lenguaje de modelado unificado" },
  { categoria: "Programación", pregunta: "¿Qué es una clase abstracta?", opciones: ["Clase que no se puede instanciar directamente", "Variable global", "Bucle", "Array"], respuesta: "Clase que no se puede instanciar directamente" },
  { categoria: "Programación", pregunta: "¿Qué es un objeto en programación orientada a objetos?", opciones: ["Instancia de una clase", "Variable", "Bucle", "Función"], respuesta: "Instancia de una clase" },
  { categoria: "Programación", pregunta: "¿Qué es una excepción?", opciones: ["Error detectado en tiempo de ejecución", "Bucle", "Variable global", "Array"], respuesta: "Error detectado en tiempo de ejecución" },
  { categoria: "Programación", pregunta: "¿Qué es try-catch?", opciones: ["Estructura para manejar excepciones", "Bucle", "Variable", "Hardware"], respuesta: "Estructura para manejar excepciones" },

  // 61-70
  { categoria: "Programación", pregunta: "¿Qué es un IDE para PHP?", opciones: ["PhpStorm", "PyCharm", "IntelliJ", "Visual Studio Code"], respuesta: "PhpStorm" },
  { categoria: "Programación", pregunta: "¿Qué es un framework MVC?", opciones: ["Patrón Modelo-Vista-Controlador", "Variable global", "Bucle", "Array"], respuesta: "Patrón Modelo-Vista-Controlador" },
  { categoria: "Programación", pregunta: "¿Qué es Bootstrap?", opciones: ["Framework CSS para diseño responsivo", "Lenguaje de programación", "Hardware", "Bucle"], respuesta: "Framework CSS para diseño responsivo" },
  { categoria: "Programación", pregunta: "¿Qué es Angular?", opciones: ["Framework de JavaScript para aplicaciones web", "Lenguaje de programación", "Variable", "Bucle"], respuesta: "Framework de JavaScript para aplicaciones web" },
  { categoria: "Programación", pregunta: "¿Qué es Vue.js?", opciones: ["Framework progresivo de JavaScript", "Lenguaje de programación", "Bucle", "Variable"], respuesta: "Framework progresivo de JavaScript" },
  { categoria: "Programación", pregunta: "¿Qué es TypeScript?", opciones: ["Superset de JavaScript con tipado", "Lenguaje interpretado", "Base de datos", "Bucle"], respuesta: "Superset de JavaScript con tipado" },
  { categoria: "Programación", pregunta: "¿Qué es un endpoint?", opciones: ["URL que responde a solicitudes HTTP", "Variable global", "Bucle", "Array"], respuesta: "URL que responde a solicitudes HTTP" },
  { categoria: "Programación", pregunta: "¿Qué es REST?", opciones: ["Arquitectura para servicios web", "Lenguaje de programación", "Variable", "Bucle"], respuesta: "Arquitectura para servicios web" },
  { categoria: "Programación", pregunta: "¿Qué es SOAP?", opciones: ["Protocolo de intercambio de mensajes XML", "Lenguaje de programación", "Bucle", "Array"], respuesta: "Protocolo de intercambio de mensajes XML" },
  { categoria: "Programación", pregunta: "¿Qué es JSON Web Token (JWT)?", opciones: ["Estándar para transmitir información segura", "Lenguaje de programación", "Variable", "Bucle"], respuesta: "Estándar para transmitir información segura" },

  // 71-80
  { categoria: "Programación", pregunta: "¿Qué es un servidor Apache?", opciones: ["Servidor web open source", "Lenguaje de programación", "Bucle", "Variable"], respuesta: "Servidor web open source" },
  { categoria: "Programación", pregunta: "¿Qué es un servidor Nginx?", opciones: ["Servidor web y proxy inverso", "Lenguaje de programación", "Bucle", "Variable"], respuesta: "Servidor web y proxy inverso" },
  { categoria: "Programación", pregunta: "¿Qué es un algoritmo de búsqueda?", opciones: ["Método para encontrar elementos en estructuras de datos", "Bucle", "Variable", "Array"], respuesta: "Método para encontrar elementos en estructuras de datos" },
  { categoria: "Programación", pregunta: "¿Qué es un algoritmo de ordenamiento?", opciones: ["Método para organizar elementos", "Bucle", "Variable", "Array"], respuesta: "Método para organizar elementos" },
  { categoria: "Programación", pregunta: "¿Qué es Big Data?", opciones: ["Conjunto masivo de datos que requieren procesamiento especial", "Lenguaje de programación", "Variable", "Bucle"], respuesta: "Conjunto masivo de datos que requieren procesamiento especial" },
  { categoria: "Programación", pregunta: "¿Qué es Cloud Computing?", opciones: ["Uso de servicios y recursos en la nube", "Lenguaje de programación", "Variable", "Bucle"], respuesta: "Uso de servicios y recursos en la nube" },
  { categoria: "Programación", pregunta: "¿Qué es IoT?", opciones: ["Internet de las cosas, dispositivos conectados", "Lenguaje de programación", "Bucle", "Variable"], respuesta: "Internet de las cosas, dispositivos conectados" },
  { categoria: "Programación", pregunta: "¿Qué es AI (Inteligencia Artificial)?", opciones: ["Simulación de inteligencia humana en máquinas", "Lenguaje de programación", "Bucle", "Variable"], respuesta: "Simulación de inteligencia humana en máquinas" },
  { categoria: "Programación", pregunta: "¿Qué es Machine Learning?", opciones: ["Aprendizaje automático de máquinas a partir de datos", "Lenguaje de programación", "Variable", "Bucle"], respuesta: "Aprendizaje automático de máquinas a partir de datos" },
  { categoria: "Programación", pregunta: "¿Qué es Deep Learning?", opciones: ["Subcampo de Machine Learning con redes neuronales", "Lenguaje de programación", "Variable", "Bucle"], respuesta: "Subcampo de Machine Learning con redes neuronales" },

  // 81-90
  { categoria: "Programación", pregunta: "¿Qué es un repositorio?", opciones: ["Lugar donde se almacena código", "Bucle", "Variable", "Hardware"], respuesta: "Lugar donde se almacena código" },
  { categoria: "Programación", pregunta: "¿Qué es Scrum?", opciones: ["Metodología ágil para desarrollo de software", "Lenguaje de programación", "Variable", "Bucle"], respuesta: "Metodología ágil para desarrollo de software" },
  { categoria: "Programación", pregunta: "¿Qué es Kanban?", opciones: ["Método ágil visual para gestión de proyectos", "Lenguaje de programación", "Variable", "Bucle"], respuesta: "Método ágil visual para gestión de proyectos" },
  { categoria: "Programación", pregunta: "¿Qué es DevOps?", opciones: ["Cultura que integra desarrollo y operaciones", "Lenguaje de programación", "Variable", "Bucle"], respuesta: "Cultura que integra desarrollo y operaciones" },
  { categoria: "Programación", pregunta: "¿Qué es CI/CD?", opciones: ["Integración y entrega continua", "Lenguaje de programación", "Variable", "Bucle"], respuesta: "Integración y entrega continua" },
  { categoria: "Programación", pregunta: "¿Qué es virtualización?", opciones: ["Creación de entornos virtuales de computadoras", "Lenguaje de programación", "Variable", "Bucle"], respuesta: "Creación de entornos virtuales de computadoras" },
  { categoria: "Programación", pregunta: "¿Qué es un contenedor (Docker)?", opciones: ["Unidad ligera para ejecutar aplicaciones", "Lenguaje de programación", "Variable", "Bucle"], respuesta: "Unidad ligera para ejecutar aplicaciones" },
  { categoria: "Programación", pregunta: "¿Qué es Kubernetes?", opciones: ["Sistema para orquestar contenedores", "Lenguaje de programación", "Variable", "Bucle"], respuesta: "Sistema para orquestar contenedores" },
  { categoria: "Programación", pregunta: "¿Qué es una arquitectura cliente-servidor?", opciones: ["Modelo donde cliente solicita servicios al servidor", "Lenguaje de programación", "Variable", "Bucle"], respuesta: "Modelo donde cliente solicita servicios al servidor" },
  { categoria: "Programación", pregunta: "¿Qué es programación funcional?", opciones: ["Paradigma basado en funciones puras y sin estado", "Bucle", "Variable", "Hardware"], respuesta: "Paradigma basado en funciones puras y sin estado" },

  // 91-100
  { categoria: "Programación", pregunta: "¿Qué es programación concurrente?", opciones: ["Ejecución de múltiples procesos al mismo tiempo", "Bucle", "Variable", "Hardware"], respuesta: "Ejecución de múltiples procesos al mismo tiempo" },
  { categoria: "Programación", pregunta: "¿Qué es programación paralela?", opciones: ["Procesamiento simultáneo para eficiencia", "Bucle", "Variable", "Hardware"], respuesta: "Procesamiento simultáneo para eficiencia" },
  { categoria: "Programación", pregunta: "¿Qué es blockchain?", opciones: ["Cadena de bloques para registrar transacciones", "Variable", "Bucle", "Array"], respuesta: "Cadena de bloques para registrar transacciones" },
  { categoria: "Programación", pregunta: "¿Qué es criptografía?", opciones: ["Técnica para proteger información mediante cifrado", "Variable", "Bucle", "Hardware"], respuesta: "Técnica para proteger información mediante cifrado" },
  { categoria: "Programación", pregunta: "¿Qué es un servidor proxy?", opciones: ["Intermediario entre cliente y servidor", "Variable", "Bucle", "Hardware"], respuesta: "Intermediario entre cliente y servidor" },
  { categoria: "Programación", pregunta: "¿Qué es un firewall?", opciones: ["Sistema de seguridad que filtra tráfico de red", "Variable", "Bucle", "Hardware"], respuesta: "Sistema de seguridad que filtra tráfico de red" },
  { categoria: "Programación", pregunta: "¿Qué es un malware?", opciones: ["Software malicioso que daña sistemas", "Variable", "Bucle", "Hardware"], respuesta: "Software malicioso que daña sistemas" },
  { categoria: "Programación", pregunta: "¿Qué es un antivirus?", opciones: ["Software que detecta y elimina malware", "Variable", "Bucle", "Hardware"], respuesta: "Software que detecta y elimina malware" },
  { categoria: "Programación", pregunta: "¿Qué es virtualización de red?", opciones: ["Simulación de recursos de red mediante software", "Variable", "Bucle", "Hardware"], respuesta: "Simulación de recursos de red mediante software" },
  { categoria: "Programación", pregunta: "¿Qué es un servicio web?", opciones: ["Aplicación accesible vía red que ofrece funcionalidad", "Variable", "Bucle", "Hardware"], respuesta: "Aplicación accesible vía red que ofrece funcionalidad" }
];
